openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::enable_qtum::status
  version: v2
  description: Query the status of QTUM/QRC20 activation task.
paths:
  /task::enable_qtum::status:
    post:
      summary: 'Enable QTUM Task: Status'
      description: Query the status of QTUM/QRC20 activation task.
      operationId: task::enable_qtum::status
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::enable_qtum::status
      responses:
        '200':
          description: Successful response for task::enable_qtum::status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_enable_qtum_status_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
