openapi: 3.0.3
info:
  title: Enable BCH with Tokens
  description: Enable BCH/tBCH along with multiple SLP tokens in a single command.
  version: 1.0.0
paths:
  /enable_bch_with_tokens:
    post:
      summary: Enable BCH with SLP tokens
      operationId: "enable_bch_with_tokens"
      tags:
        - Coin Activation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userpass:
                  type: string
                method:
                  type: string
                  enum: [enable_bch_with_tokens]
                mmrpc:
                  type: string
                params:
                  type: object
                  properties:
                    ticker:
                      type: string
                    bchd_urls:
                      type: array
                      items:
                        type: string
                    mode:
                      type: object
                    tx_history:
                      type: boolean
                    slp_tokens_requests:
                      type: array
                      items:
                        type: object
                    address_format:
                      type: object
                    allow_slp_unsafe_conf:
                      type: boolean
                    get_balances:
                      type: boolean
                    required_confirmations:
                      type: integer
                    requires_notarization:
                      type: boolean
                    utxo_merge_params:
                      type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  mmrpc:
                    type: string
                  result:
                    type: object
                  id:
                    type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error 