openapi: 3.0.3
info:
  title: Enable SLP
  description: Activate additional SLP tokens.
  version: 1.0.0
paths:
  /enable_slp:
    post:
      summary: Enable SLP token
      operationId: "enable_slp"
      tags:
        - Coin Activation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userpass:
                  type: string
                method:
                  type: string
                  enum: [enable_slp]
                mmrpc:
                  type: string
                params:
                  type: object
                  properties:
                    ticker:
                      type: string
                    activation_params:
                      type: object
                      properties:
                        required_confirmations:
                          type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  mmrpc:
                    type: string
                  result:
                    type: object
                  id:
                    type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error 