openapi: 3.0.3
info:
  title: Enable Tendermint with Assets
  description: Activate Tendermint coins and IBC assets in a single command.
  version: 1.0.0
paths:
  /enable_tendermint_with_assets:
    post:
      summary: Enable Tendermint with IBC assets
      operationId: "enable_tendermint_with_assets"
      tags:
        - Coin Activation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userpass:
                  type: string
                method:
                  type: string
                  enum: [enable_tendermint_with_assets]
                mmrpc:
                  type: string
                params:
                  type: object
                  properties:
                    ticker:
                      type: string
                    mm2:
                      type: integer
                    tokens_params:
                      type: array
                      items:
                        type: object
                    nodes:
                      type: array
                      items:
                        type: object
                    priv_key_policy:
                      type: string
                    tx_history:
                      type: boolean
                    required_confirmations:
                      type: integer
                    requires_notarization:
                      type: boolean
                    get_balances:
                      type: boolean
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  mmrpc:
                    type: string
                  result:
                    type: object
                  id:
                    type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error 