openapi: 3.0.3
info:
  title: 1inch v6.0 Classic Swap Create
  description: Create a swap using the 1inch v6.0 classic aggregator.
  version: 1.0.0
paths:
  /one_inch_v6_0_classic_swap_create:
    post:
      summary: Create a 1inch v6.0 classic swap
      operationId: "one_inch_v6_0_classic_swap_create"
      tags:
        - 1inch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userpass:
                  type: string
                method:
                  type: string
                  enum: [one_inch_v6_0_classic_swap_create]
                mmrpc:
                  type: string
                params:
                  type: object
                  properties:
                    fromTokenAddress:
                      type: string
                    toTokenAddress:
                      type: string
                    amount:
                      type: string
                    fromAddress:
                      type: string
                    slippage:
                      type: number
                    disableEstimate:
                      type: boolean
                    allowPartialFill:
                      type: boolean
      responses:
        '200':
          description: Swap created
          content:
            application/json:
              schema:
                type: object
                properties:
                  tx:
                    type: object
                  toTokenAmount:
                    type: string
                  fromTokenAmount:
                    type: string
        '400':
          description: Bad request
        '500':
          description: Internal server error 