openapi: 3.0.3
info:
  title: Query NFT Database Tables
  description: Query the local NFT database tables for information.
  version: 1.0.0
paths:
  /query_nft_database_tables:
    post:
      operationId: "query_nft_database_tables"
      summary: Query NFT database tables
      tags:
        - NonFungibleTokens
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                table:
                  type: string
                  description: Name of the table to query.
                query:
                  type: string
                  description: SQL query to execute.
      responses:
        '200':
          description: Query result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      type: object 