openapi: 3.0.3
info:
  title: Get Current MTP
  description: Returns the Median Time Past (MTP) from electrum servers for UTXO coins.
  version: 1.0.0
paths:
  /utils/get_current_mtp:
    post:
      operationId: "utils_get_current_mtp"
      summary: Get current MTP
      tags:
        - utils
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coin:
                  type: string
                  description: A compatible (UTXO) coin's ticker
                id:
                  type: integer
                  description: Optional. Identifies a request to allow matching it with a response.
              required:
                - coin
      responses:
        '200':
          description: MTP returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  mtp:
                    type: integer
                  id:
                    type: integer
        '400':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_type:
                    type: string 