openapi: 3.0.3
info:
  title: Update Version Stat Collection
  description: Updates the polling interval for version stats collection.
  version: 1.0.0
paths:
  /utils/update_version_stat_collection:
    post:
      operationId: "utils_update_version_stat_collection"
      summary: Update version stat collection interval
      tags:
        - utils
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                interval:
                  type: integer
                  description: Polling rate (in seconds) to query node versions
              required:
                - interval
      responses:
        '200':
          description: Interval updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
        '400':
          description: Error - stats collection not running
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_type:
                    type: string 