openapi: 3.0.3
info:
  title: Get Public Key Hash
  description: Returns the RIPEMD-160 hash version of your public key.
  version: 1.0.0
paths:
  /utils/get_public_key_hash:
    post:
      operationId: "utils_get_public_key_hash"
      summary: Get public key hash
      tags:
        - utils
      requestBody:
        required: false
      responses:
        '200':
          description: Public key hash returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  public_key_hash:
                    type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_type:
                    type: string 