openapi: 3.0.3
info:
  title: Get Mnemonic
  description: Returns the user's mnemonic seed phrase, in encrypted or plain text format.
  version: 1.0.0
paths:
  /utils/get_mnemonic:
    post:
      operationId: "utils_get_mnemonic"
      summary: Get mnemonic
      tags:
        - utils
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                format:
                  type: string
                  enum: [encrypted, plaintext]
                  description: Either 'encrypted' or 'plaintext'. Defaults to 'encrypted'.
                password:
                  type: string
                  description: The password to decrypt your stored mnemonic phrase. Only required if 'plaintext' format is requested.
      responses:
        '200':
          description: Mnemonic returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  format:
                    type: string
                  mnemonic:
                    type: string
                  encrypted_mnemonic_data:
                    type: object
        '400':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_type:
                    type: string 