openapi: 3.0.3
info:
  title: Change Mnemonic Password
  description: Update the password used to encrypt a mnemonic phrase in the local database.
  version: 1.0.0
paths:
  /utils/change_mnemonic_password:
    post:
      operationId: "utils_change_mnemonic_password"
      summary: Change mnemonic password
      tags:
        - utils
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                  description: The active mnemonic password for your wallet
                new_password:
                  type: string
                  description: The new password to use for encrypting your active mnemonic password
              required:
                - current_password
                - new_password
      responses:
        '200':
          description: Password changed successfully
          content:
            application/json:
              schema:
                type: object
                nullable: true
        '400':
          description: Error - wrong password
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_type:
                    type: string 