openapi: 3.0.3
info:
  title: Sign Message
  description: Sign a message for any supported coin, proving ownership of a wallet address.
  version: 1.0.0
paths:
  /utils/message_signing_sign_message:
    post:
      operationId: "utils_message_signing_sign_message"
      summary: Sign message
      tags:
        - utils
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coin:
                  type: string
                  description: The coin to sign a message with
                message:
                  type: string
                  description: The message you want to sign
                address:
                  type: object
                  description: Optional, HD wallets only. AddressPath object for signing the message.
      responses:
        '200':
          description: Signature generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  signature:
                    type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_type:
                    type: string 