openapi: 3.0.3
info:
  title: Get Public Key
  description: Returns the compressed secp256k1 pubkey corresponding to the user's seed phrase.
  version: 1.0.0
paths:
  /utils/get_public_key:
    post:
      operationId: "utils_get_public_key"
      summary: Get public key
      tags:
        - utils
      requestBody:
        required: false
      responses:
        '200':
          description: Public key returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  public_key:
                    type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_type:
                    type: string 