openapi: 3.0.3
info:
  title: Get Enabled Coins
  description: Returns data of coins that are currently enabled on the user's Komodo DeFi Framework API node.
  version: 1.0.0
paths:
  /utils/get_enabled_coins:
    post:
      operationId: "utils_get_enabled_coins"
      summary: Get enabled coins
      tags:
        - utils
      requestBody:
        required: false
      responses:
        '200':
          description: List of enabled coins
          content:
            application/json:
              schema:
                type: object
                properties:
                  coins:
                    type: array
                    items:
                      type: object
                      properties:
                        ticker:
                          type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_type:
                    type: string 