openapi: 3.0.3
info:
  title: Start Version Stat Collection
  description: Initiates storing version statistics for nodes registered via add_node_to_version_stat.
  version: 1.0.0
paths:
  /utils/start_version_stat_collection:
    post:
      operationId: "utils_start_version_stat_collection"
      summary: Start version stat collection
      tags:
        - utils
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                interval:
                  type: integer
                  description: Polling rate (in seconds) to check node versions
              required:
                - interval
      responses:
        '200':
          description: Stats collection started
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
        '400':
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_type:
                    type: string 