openapi: 3.0.3
info:
  title: Stop Version Stat Collection
  description: Stops the collection of version stats at the end of the current loop interval.
  version: 1.0.0
paths:
  /utils/stop_version_stat_collection:
    post:
      operationId: "utils_stop_version_stat_collection"
      summary: Stop version stat collection
      tags:
        - utils
      requestBody:
        required: false
      responses:
        '200':
          description: Stats collection stopped
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
        '400':
          description: Error - stats collection not running
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  error_type:
                    type: string 