openapi: 3.0.3
info:
  title: Create New Account
  description: Create a new account in the wallet.
  version: 1.0.0
paths:
  /wallet/task_managed/create_new_account:
    post:
      operationId: "wallet_task_managed_create_new_account"
      summary: Create new account
      tags:
        - Wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_name:
                  type: string
                  description: Name for the new account
      responses:
        '200':
          description: New account created
      security:
        - userpass: [] 