openapi: 3.0.3
info:
  title: Get Raw Transaction
  description: Get the raw transaction data for a given transaction ID.
  version: 1.0.0
paths:
  /wallet/tx/get_raw_transaction:
    get:
      operationId: "wallet_tx_get_raw_transaction"
      summary: Get raw transaction
      tags:
        - Wallet
      parameters:
        - in: query
          name: txid
          schema:
            type: string
          required: true
          description: Transaction ID
      responses:
        '200':
          description: Raw transaction data
          content:
            application/json:
              schema:
                type: object
                properties:
                  raw:
                    type: string
                    description: Raw transaction hex
      security:
        - userpass: [] 