openapi: 3.0.3
info:
  title: Get Wallet Names
  description: Get the list of wallet names.
  version: 1.0.0
paths:
  /wallet/get_wallet_names:
    get:
      operationId: "wallet_get_wallet_names"
      summary: Get wallet names
      tags:
        - Wallet
      responses:
        '200':
          description: List of wallet names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      security:
        - userpass: [] 