openapi: 3.0.3
info:
  title: Remove Delegation
  description: Remove a staking delegation from the wallet.
  version: 1.0.0
paths:
  /wallet/staking/remove_delegation:
    post:
      operationId: "wallet_staking_remove_delegation"
      summary: Remove staking delegation
      tags:
        - Wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                delegate_address:
                  type: string
                  description: Address to remove delegation from
      responses:
        '200':
          description: Delegation removed
      security:
        - userpass: [] 