openapi: 3.0.3
info:
  title: My Transaction History
  description: Get the transaction history for the wallet.
  version: 1.0.0
paths:
  /wallet/tx/my_tx_history:
    get:
      operationId: "wallet_tx_my_tx_history"
      summary: Get transaction history
      tags:
        - Wallet
      responses:
        '200':
          description: Transaction history
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
      security:
        - userpass: [] 