openapi: 3.0.3
info:
  title: Get New Address
  description: Get a new address for the wallet account.
  version: 1.0.0
paths:
  /wallet/task_managed/get_new_address:
    get:
      operationId: "wallet_task_managed_get_new_address"
      summary: Get new address
      tags:
        - Wallet
      responses:
        '200':
          description: New address
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                    description: New wallet address
      security:
        - userpass: [] 