openapi: 3.0.3
info:
  title: Set Swap Transaction Fee Policy
  description: Set the swap transaction fee policy.
  version: 1.0.0
paths:
  /wallet/fee_management/set_swap_transaction_fee_policy:
    post:
      operationId: "wallet_fee_management_set_swap_transaction_fee_policy"
      summary: Set swap transaction fee policy
      tags:
        - Wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                policy:
                  type: string
                  description: New fee policy
      responses:
        '200':
          description: Fee policy updated
      security:
        - userpass: [] 