openapi: 3.0.3
info:
  title: Withdraw (TX)
  description: Withdraw funds from the wallet via transaction.
  version: 1.0.0
paths:
  /wallet/tx/withdraw:
    post:
      operationId: "wallet_tx_withdraw"
      summary: Withdraw funds (TX)
      tags:
        - Wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  description: Destination address
                amount:
                  type: string
                  description: Amount to withdraw
      responses:
        '200':
          description: Withdrawal transaction successful
      security:
        - userpass: [] 