openapi: 3.0.3
info:
  title: Withdraw
  description: Withdraw funds from the wallet account.
  version: 1.0.0
paths:
  /wallet/task_managed/withdraw:
    post:
      operationId: "wallet_task_managed_withdraw"
      summary: Withdraw funds
      tags:
        - Wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  description: Destination address
                amount:
                  type: string
                  description: Amount to withdraw
      responses:
        '200':
          description: Withdrawal successful
      security:
        - userpass: [] 