openapi: 3.0.3
info:
  title: Scan For New Addresses
  description: Scan the wallet for new addresses.
  version: 1.0.0
paths:
  /wallet/task_managed/scan_for_new_addresses:
    post:
      operationId: "wallet_task_managed_scan_for_new_addresses"
      summary: Scan for new addresses
      tags:
        - Wallet
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Scan started
      security:
        - userpass: [] 