openapi: 3.0.3
info:
  title: Account Balance
  description: Get the account balance for a wallet.
  version: 1.0.0
paths:
  /wallet/task_managed/account_balance:
    get:
      operationId: "wallet_task_managed_account_balance"
      summary: Get account balance
      tags:
        - Wallet
      responses:
        '200':
          description: Account balance
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: string
                    description: Account balance
      security:
        - userpass: [] 