openapi: 3.0.3
info:
  title: Get Swap Transaction Fee Policy
  description: Get the current swap transaction fee policy.
  version: 1.0.0
paths:
  /wallet/fee_management/get_swap_transaction_fee_policy:
    get:
      operationId: "wallet_fee_management_get_swap_transaction_fee_policy"
      summary: Get swap transaction fee policy
      tags:
        - Wallet
      responses:
        '200':
          description: Swap transaction fee policy
          content:
            application/json:
              schema:
                type: object
                properties:
                  policy:
                    type: string
                    description: Current fee policy
      security:
        - userpass: [] 