openapi: 3.0.3
info:
  title: ZHTLC Transaction History
  description: Get the ZHTLC transaction history for the wallet.
  version: 1.0.0
paths:
  /wallet/tx/zhtlc_tx_history:
    get:
      operationId: "wallet_tx_zhtlc_tx_history"
      summary: Get ZHTLC transaction history
      tags:
        - Wallet
      responses:
        '200':
          description: ZHTLC transaction history
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
      security:
        - userpass: [] 