openapi: 3.0.3
info:
  title: Get Staking Infos
  description: Get staking information for the wallet.
  version: 1.0.0
paths:
  /wallet/staking/get_staking_infos:
    get:
      operationId: "wallet_staking_get_staking_infos"
      summary: Get staking infos
      tags:
        - Wallet
      responses:
        '200':
          description: Staking information
          content:
            application/json:
              schema:
                type: object
                properties:
                  infos:
                    type: array
                    items:
                      type: object
      security:
        - userpass: [] 