openapi: 3.0.3
info:
  title: Get ETH Estimated Fee Per Gas
  description: Get estimated fee per gas for ETH transactions.
  version: 1.0.0
paths:
  /wallet/fee_management/get_eth_estimated_fee_per_gas:
    get:
      operationId: "wallet_fee_management_get_eth_estimated_fee_per_gas"
      summary: Get ETH estimated fee per gas
      tags:
        - Wallet
      responses:
        '200':
          description: Estimated fee per gas
          content:
            application/json:
              schema:
                type: object
                properties:
                  gasPrice:
                    type: string
                    description: Estimated gas price in wei
      security:
        - userpass: [] 