openapi: 3.0.3
info:
  title: Add Delegation
  description: Add a staking delegation to the wallet.
  version: 1.0.0
paths:
  /wallet/staking/add_delegation:
    post:
      operationId: "wallet_staking_add_delegation"
      summary: Add staking delegation
      tags:
        - Wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                delegate_address:
                  type: string
                  description: Address to delegate to
                amount:
                  type: string
                  description: Amount to delegate
      responses:
        '200':
          description: Delegation added
      security:
        - userpass: [] 