openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - orderbook_depth
  version: v1
  description: The orderbook_depth method returns the number of asks and bids for
    the specified trading pairs.
paths:
  /orderbook_depth:
    post:
      summary: Orderbook Depth
      description: The orderbook_depth method returns the number of asks and bids
        for the specified trading pairs.
      operationId: orderbook_depth
      tags:
      - orderbook_depth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - orderbook_depth
      responses:
        '200':
          description: Successful response for orderbook_depth
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orderbook_depth_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
