openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - stream::tx_history::enable
  version: v2
  description: Using this method, you can enable transaction history events streaming
    for a specific coin.
paths:
  /stream::tx_history::enable:
    post:
      summary: Enable Transaction History Streaming
      description: Using this method, you can enable transaction history events streaming
        for a specific coin.
      operationId: stream::tx_history::enable
      tags:
      - stream
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - stream::tx_history::enable
                params:
                  type: object
                  properties:
                    client_id:
                      description: This ID can be used to access data via [http://localhost:7783/event-stream?id=1](http://localhost:7783/event-stream?id=1)
                      type: integer
                      default: '`0`'
                    coin:
                      description: Ticker of the coin to activate streaming for. The
                        coin must be activated first.
                      type: string
                      default: '-'
                  required:
                  - coin
      responses:
        '200':
          description: Successful response for stream::tx_history::enable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_tx_history_enable_Response'
              example:
                mmrpc: '2.0'
                result:
                  streamer_id: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
