openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::init_trezor::user_action
  version: v2
  description: Send user action (PIN or passphrase) to the Trezor device during initialisation
    in the Komodo DeFi Framework API.
paths:
  /task::init_trezor::user_action:
    post:
      summary: task::init_trezor::user_action
      description: Send user action (PIN or passphrase) to the Trezor device during
        initialisation in the Komodo DeFi Framework API.
      operationId: task::init_trezor::user_action
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::init_trezor::user_action
      responses:
        '200':
          description: Successful response for task::init_trezor::user_action
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_init_trezor_user_action_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
