openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::enable_utxo
  version: v2
  description: Overview of task managed activation methods for UTXO coins like KMD,
    LTC, BTC, and DOGE.
paths:
  /task::enable_utxo:
    post:
      summary: Enable UTXO Task Overview
      description: Overview of task managed activation methods for UTXO coins like
        KMD, LTC, BTC, and DOGE.
      operationId: task::enable_utxo
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::enable_utxo
      responses:
        '200':
          description: Successful response for task::enable_utxo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_enable_utxo_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
