openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - tx
  version: v2
  description: An overview of the transaction methods in the Komodo DeFi Framework
    API.
paths:
  /tx:
    post:
      summary: 'Komodo DeFi Framework Method Overview: Transaction Methods'
      description: An overview of the transaction methods in the Komodo DeFi Framework
        API.
      operationId: tx
      tags:
      - tx
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - tx
      responses:
        '200':
          description: Successful response for tx
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tx_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
