openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - get_eth_estimated_fee_per_gas
  version: v2
  description: Method description for get_eth_estimated_fee_per_gas
paths:
  /get_eth_estimated_fee_per_gas:
    post:
      summary: Get ETH Estimated Fee per Gas
      description: Method description for get_eth_estimated_fee_per_gas
      operationId: get_eth_estimated_fee_per_gas
      tags:
      - get_eth_estimated_fee_per_gas
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - get_eth_estimated_fee_per_gas
                params:
                  type: object
                  properties:
                    coin:
                      description: Ticker of the coin/asset for which you want to
                        start the gas fee estimator.
                      type: string
                    estimator_type:
                      description: A standard [EstimatorTypeEnum](/komodo-defi-framework/api/common_structures/enums/#estimator-type-enum)
                        enum. If set to `Provider`, users must set the `gas_api` setting
                        in their [MM2.json file](/komodo-defi-framework/setup/configure-mm2-json/)
                        to source recommended fee values from third-party providers
                        [Infura](https://www.infura.io/) or [Blocknative](https://www.blocknative.com/).
                      $ref: '#/components/schemas/estimator-type-enum'
                  required:
                  - coin
                  - estimator_type
      responses:
        '200':
          description: Successful response for get_eth_estimated_fee_per_gas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_eth_estimated_fee_per_gas_Response'
              example:
                mmrpc: '2.0'
                result:
                  base_fee: string_value
                  low\.max_priority_fee_per_gas: string_value
                  low\.max_fee_per_gas: string_value
                  low\.min_wait_time: string_value
                  low\.max_wait_time: string_value
                  medium.max_priority_fee_per_gas: string_value
                  medium.max_fee_per_gas: string_value
                  medium.min_wait_time: string_value
                  medium.max_wait_time: string_value
                  high.max_priority_fee_per_gas: string_value
                  high.max_fee_per_gas: string_value
                  high.min_wait_time: string_value
                  high.max_wait_time: string_value
                  source: string_value
                  base_fee_trend: string_value
                  priority_fee_trend: string_value
                  units: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
