openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - experimental::staking::undelegate
  version: v2
  description: Method description for experimental::staking::undelegate
paths:
  /experimental::staking::undelegate:
    post:
      summary: Remove Delegation
      description: Method description for experimental::staking::undelegate
      operationId: experimental::staking::undelegate
      tags:
      - experimental
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - experimental::staking::undelegate
      responses:
        '200':
          description: Successful response for experimental::staking::undelegate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/experimental_staking_undelegate_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
