openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Api-Rpc-Legacy API
  version: v1
  description: OpenAPI specification for the api-rpc-legacy methods.
paths:
  /api-rpc-legacy:
    post:
      summary: API (Legacy Methods)
      description: This section contains the Legacy Komodo DeFi Framework methods
        that are currently being ported to the 2.0 version.
      operationId: api-rpc-legacy
      tags:
      - api-rpc-legacy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - api-rpc-legacy
      responses:
        '200':
          description: Successful response for api-rpc-legacy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-rpc-legacy_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
