openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Coins Needed For Kick Start V1 API
  version: v1
  description: OpenAPI specification for the coins_needed_for_kick_start_v1 methods.
paths:
  /coins_needed_for_kick_start:
    post:
      summary: Coins Needed For Kick Start
      description: Learn how to kick-start interrupted swaps on the Komodo DeFi Framework
        API by activating the necessary coins using the coins_needed_for_kick_start
        method.
      operationId: coins_needed_for_kick_start
      tags:
      - coins_needed_for_kick_start
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - coins_needed_for_kick_start
      responses:
        '200':
          description: Successful response for coins_needed_for_kick_start
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/coins_needed_for_kick_start_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
