openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Electrum V1 API
  version: v1
  description: OpenAPI specification for the electrum_v1 methods.
paths:
  /electrum:
    post:
      summary: electrum
      description: Activate a coin using the Electrum method in the Komodo DeFi Framework
        API.
      operationId: electrum
      tags:
      - electrum
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - electrum
      responses:
        '200':
          description: Successful response for electrum
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/electrum_Response'
              example:
                mmrpc: '2.0'
                result:
                  address: string_value
                  balance: string_value
                  unspendable_balance: string_value
                  coin: string_value
                  required_confirmations: {}
                  mature_confirmations: {}
                  requires_notarization: {}
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
