openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Get Gossip Mesh V1 API
  version: v1
  description: OpenAPI specification for the get_gossip_mesh_v1 methods.
paths:
  /get_gossip_mesh:
    post:
      summary: Get Gossip Mesh
      description: The get_gossip_mesh method returns an array of peerIDs added to
        a topics
      operationId: get_gossip_mesh
      tags:
      - get_gossip_mesh
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - get_gossip_mesh
      responses:
        '200':
          description: Successful response for get_gossip_mesh
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_gossip_mesh_Response'
              example:
                mmrpc: '2.0'
                result:
                  Topic-PeerID map: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
