openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Import Swaps V1 API
  version: v1
  description: OpenAPI specification for the import_swaps_v1 methods.
paths:
  /import_swaps:
    post:
      summary: Import Swaps
      description: The import_swaps method imports to the local database the swaps
        data that was exported from another Komodo DeFi Framework API instance.
      operationId: import_swaps
      tags:
      - import_swaps
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - import_swaps
      responses:
        '200':
          description: Successful response for import_swaps
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/import_swaps_Response'
              example:
                mmrpc: '2.0'
                result:
                  result.imported: string_value
                  result.skipped: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
