openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Kmd Rewards Info V1 API
  version: v1
  description: OpenAPI specification for the kmd_rewards_info_v1 methods.
paths:
  /kmd_rewards_info:
    post:
      summary: KMD Rewards Info
      description: The kmd_rewards_info method returns information about the active
        user rewards that can be claimed by an address
      operationId: kmd_rewards_info
      tags:
      - kmd_rewards_info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - kmd_rewards_info
      responses:
        '200':
          description: Successful response for kmd_rewards_info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/kmd_rewards_info_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: {}
                  tx_hash: string_value
                  height: 123
                  output_index: 123
                  amount: string_value
                  locktime: 123
                  accrued_rewards: {}
                  accrue_start_at: 123
                  accrue_stop_at: 123
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
