openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Lightning-Common-Structures API
  version: v1
  description: OpenAPI specification for the lightning-common-structures methods.
paths:
  /lightning-common-structures:
    post:
      summary: Lightning Common Structures
      description: Lightning Network common structures for Komodo DeFi Framework API.
      operationId: lightning-common-structures
      tags:
      - lightning-common-structures
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning-common-structures
      responses:
        '200':
          description: Successful response for lightning-common-structures
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning-common-structures_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
