openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Nfts-Common-Structures API
  version: v1
  description: OpenAPI specification for the nfts-common-structures methods.
paths:
  /nfts-common-structures:
    post:
      summary: 'Komodo DeFi SDK Common Structures: Non-Fungible Tokens'
      description: Starting with version beta-2.1.3434, the Komodo DeFi SDK supports
        the standardized protocol format called mmrpc 2.0.
      operationId: nfts-common-structures
      tags:
      - nfts-common-structures
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - nfts-common-structures
      responses:
        '200':
          description: Successful response for nfts-common-structures
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nfts-common-structures_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
