openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Orders History By Filter V1 API
  version: v1
  description: OpenAPI specification for the orders_history_by_filter_v1 methods.
paths:
  /orders_history_by_filter:
    post:
      summary: Orders History By Filter
      description: The orders_history_by_filter method returns all orders, whether
        active or inactive, that match the selected filters.
      operationId: orders_history_by_filter
      tags:
      - orders_history_by_filter
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - orders_history_by_filter
      responses:
        '200':
          description: Successful response for orders_history_by_filter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/orders_history_by_filter_Response'
              example:
                mmrpc: '2.0'
                result:
                  details: {}
                  found_records: {}
                  orders: {}
                  warnings: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
