openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Setprice API
  version: v1
  description: OpenAPI specification for the setprice methods.
paths:
  /setprice:
    post:
      summary: Setprice
      description: The setprice method places an order on the orderbook, and it relies
        on this node acting as a maker, also called a Bob node.
      operationId: setprice
      tags:
      - setprice
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - setprice
      responses:
        '200':
          description: Successful response for setprice
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/setprice_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: {}
                  base: string_value
                  rel: string_value
                  price: string_value
                  price_rat: {}
                  max_base_vol: string_value
                  max_base_vol_rat: {}
                  min_base_vol: string_value
                  min_base_vol_rat: {}
                  created_at: {}
                  updated_at: {}
                  matches: {}
                  started_swaps: string_value
                  uuid: string_value
                  conf_settings: {}
                  base_orderbook_ticker: string_value
                  rel_orderbook_ticker: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
