openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - clear_nft_db
  version: v2
  description: Method description for clear_nft_db
paths:
  /clear_nft_db:
    post:
      summary: Clear NFT Database
      description: Method description for clear_nft_db
      operationId: clear_nft_db
      tags:
      - clear_nft_db
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - clear_nft_db
      responses:
        '200':
          description: Successful response for clear_nft_db
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/clear_nft_db_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
