openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - enable_nft
  version: v2
  description: The enable_nft method activates NFT-like tokens on the platform if
    the NFT network was already activated, but without the nft_req parameter.
paths:
  /enable_nft:
    post:
      summary: Enable NFT
      description: The enable_nft method activates NFT-like tokens on the platform
        if the NFT network was already activated, but without the nft_req parameter.
      operationId: enable_nft
      tags:
      - enable_nft
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - enable_nft
      responses:
        '200':
          description: Successful response for enable_nft
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/enable_nft_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
