openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::scan_for_new_addresses
  version: v2
  description: Overview of scan for new addresses task-managed methods in the Komodo
    DeFi Framework API.
paths:
  /task::scan_for_new_addresses:
    post:
      summary: Scan for New Addresses Task
      description: Overview of scan for new addresses task-managed methods in the
        Komodo DeFi Framework API.
      operationId: task::scan_for_new_addresses
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::scan_for_new_addresses
      responses:
        '200':
          description: Successful response for task::scan_for_new_addresses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_scan_for_new_addresses_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
