openapi: 3.0.0
info:
  title: Komodo DeFi Framework - 1Inch V6 0 Classic Swap Liquidity Sources API
  version: v2
  description: OpenAPI specification for the 1inch_v6_0_classic_swap_liquidity_sources
    methods.
paths:
  /1inch_v6_0_classic_swap_liquidity_sources:
    post:
      summary: 1inch v6.0 Classic Swap Liquidity Sources
      description: Method description for 1inch_v6_0_classic_swap_liquidity_sources
      operationId: 1inch_v6_0_classic_swap_liquidity_sources
      tags:
      - 1inch_v6_0_classic_swap_liquidity_sources
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - 1inch_v6_0_classic_swap_liquidity_sources
      responses:
        '200':
          description: Successful response for 1inch_v6_0_classic_swap_liquidity_sources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/1inch_v6_0_classic_swap_liquidity_sources_Response'
              example:
                mmrpc: '2.0'
                result:
                  dst_amount: {}
                  protocols: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
