openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Add Node To Version Stat API
  version: v2
  description: OpenAPI specification for the add_node_to_version_stat methods.
paths:
  /add_node_to_version_stat:
    post:
      summary: Add Node to Version Stat
      description: The add_node_to_version_stat method adds a Node
      operationId: add_node_to_version_stat
      tags:
      - add_node_to_version_stat
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - add_node_to_version_stat
                params:
                  type: object
                  properties:
                    address:
                      description: The IP address of the node
                      type: string
                    name:
                      description: The name assigned to the node
                      type: string
                    peer_id:
                      description: The node's unique Peer ID
                      type: string
                  required:
                  - address
                  - name
                  - peer_id
      responses:
        '200':
          description: Successful response for add_node_to_version_stat
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/add_node_to_version_stat_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
