openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Api-Rpc-Protocol-V2-0-Dev API
  version: v2
  description: OpenAPI specification for the api-rpc-protocol-v2-0-dev methods.
paths:
  /api-rpc-protocol-v2-0-dev:
    post:
      summary: API RPC Protocol v2.0 (Dev)
      description: Komodo DeFi Framework API now supports mmrpc 2.0 protocol format,
        providing a standardized format for requests, successful responses, and error
        responses.
      operationId: api-rpc-protocol-v2-0-dev
      tags:
      - api-rpc-protocol-v2-0-dev
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - api-rpc-protocol-v2-0-dev
      responses:
        '200':
          description: Successful response for api-rpc-protocol-v2-0-dev
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-rpc-protocol-v2-0-dev_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
