openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Peer Connection Healthcheck API
  version: v2
  description: OpenAPI specification for the peer_connection_healthcheck methods.
paths:
  /peer_connection_healthcheck:
    post:
      summary: Peer Connection Healthcheck
      description: The peer_connection_healthcheck method checks if a peer is connected
        to the KDF network.
      operationId: peer_connection_healthcheck
      tags:
      - peer_connection_healthcheck
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - peer_connection_healthcheck
                params:
                  type: object
                  properties:
                    peer_address:
                      description: The peer address to check for connectivity
                      type: string
                  required:
                  - peer_address
      responses:
        '200':
          description: Successful response for peer_connection_healthcheck
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/peer_connection_healthcheck_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: true
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
