openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Withdraw API
  version: v2
  description: OpenAPI specification for the withdraw methods.
paths:
  /withdraw:
    post:
      summary: Withdraw
      description: The withdraw method generates, signs, and returns a transaction
        that transfers the amount of coin to the address indicated in the to argument.
      operationId: withdraw
      tags:
      - withdraw
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - withdraw
                params:
                  type: object
                  properties:
                    amount:
                      description: The amount the user desires to withdraw, ignored
                        when `max=true`.
                      type: string
                      default: '-'
                    broadcast:
                      description: Optional, defaults to `false`. When `false`, signed
                        transaction hex must be broadcast manually with [send\_raw\_transaction](/komodo-defi-framework/api/legacy/send_raw_transaction/).
                        Must be set to `true` for Metamask managed transactions.
                      type: boolean
                      default: '`false`'
                    coin:
                      description: The name of the coin the user desires to withdraw.
                      type: string
                      default: '-'
                    fee:
                      description: A standard [FeeInfo](/komodo-defi-framework/api/common_structures/wallet/#fee-info)
                        object.
                      type: object
                      default: '-'
                    from:
                      description: HD wallets only. A standard [WithdrawFromInfo](/komodo-defi-framework/api/common_structures/wallet/#withdraw-from-info)
                        object.
                      type: object
                      default: '-'
                    ibc_source_channel:
                      description: Tendermint IBC transfers only. The source channel
                        for the [IBC](https://tutorials.cosmos.network/academy/3-ibc/1-what-is-ibc.html)
                        transaction.
                      type: integer
                      default: '-'
                    max:
                      description: Withdraw the maximum available amount.
                      type: boolean
                      default: '`false`'
                    memo:
                      description: Adds a transaction memo for compatible coins (e.g.,
                        Tendermint ecosystem).
                      type: string
                      default: '-'
                    to:
                      description: Coins are withdrawn to this address.
                      type: string
                      default: '-'
                  required:
                  - coin
                  - to
      responses:
        '200':
          description: Successful response for withdraw
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/withdraw_Response'
              example:
                mmrpc: '2.0'
                result:
                  coin: string_value
                  fee_details: {}
                  from: string_value
                  kmd_rewards: {}
                  kmd_rewards.amount: string_value
                  kmd_rewards.claimed_by_me: {}
                  my_balance_change: string_value
                  received_by_me: string_value
                  spent_by_me: string_value
                  to: string_value
                  total_amount: string_value
                  tx_hash: string_value
                  tx_hex: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
