openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - lightning::activation
  version: v2
  description: Overview of Lightning Network initialization task-managed methods in
    the Komodo DeFi Framework API.
paths:
  /lightning::activation:
    post:
      summary: Lightning Network Initialization Tasks Overview
      description: Overview of Lightning Network initialization task-managed methods
        in the Komodo DeFi Framework API.
      operationId: lightning::activation
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::activation
      responses:
        '200':
          description: Successful response for lightning::activation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_activation_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
