openapi: 3.0.3
info:
  title: Komodo DeFi Framework Activation API
  version: 2.0.0
  description: 'Focused OpenAPI specification for activation endpoints in the Komodo DeFi Framework.


    For the complete API specification, see the main openapi.yaml file.'
servers:
- url: /
  description: Local Komodo DeFi Framework instance
tags:
- name: Coin Activation
  description: Methods for activating and managing coins and tokens
paths:
  /v2/enable_bch_with_tokens:
    $ref: ./paths/v2/enable_bch_with_tokens.yaml
  /v2/enable_erc20:
    $ref: ./paths/v2/enable_erc20.yaml
  /v2/enable_eth_with_tokens:
    $ref: ./paths/v2/enable_eth_with_tokens.yaml
  /v2/enable_nft:
    $ref: ./paths/v2/enable_nft.yaml
  /v2/enable_slp:
    $ref: ./paths/v2/enable_slp.yaml
  /v2/enable_tendermint_token:
    $ref: ./paths/v2/enable_tendermint_token.yaml
  /v2/enable_tendermint_with_assets:
    $ref: ./paths/v2/enable_tendermint_with_assets.yaml
components:
  securitySchemes:
    userpass:
      type: apiKey
      in: header
      name: userpass
      description: "The API key for authentication. Use the 'userpass' value from your \nKomodo DeFi Framework instance configuration.\n"
  schemas:
    Common:
      $ref: ./components/schemas/Common.yaml
    Activation:
      $ref: ./components/schemas/Activation.yaml
security:
- userpass: []
