openapi: 3.0.3
info:
  title: Komodo DeFi Framework Experimental API
  version: 2.0.0
  description: 'Focused OpenAPI specification for experimental endpoints in the Komodo
    DeFi Framework.


    For the complete API specification, see the main openapi.yaml file.'
servers:
- url: /
  description: Local Komodo DeFi Framework instance
tags:
- name: Experimental
  description: Methods for experimental
paths:
  /v2/experimental_staking:
    $ref: ./paths/v2/experimental/staking.yaml
  /v2/experimental_staking_query_ongoing_undelegations:
    $ref: ./paths/v2/experimental/staking/query/ongoing_undelegations.yaml
  /v2/experimental_staking_delegate:
    $ref: ./paths/v2/experimental/staking/delegate.yaml
  /v2/experimental_staking_query_delegations:
    $ref: ./paths/v2/experimental/staking/query/delegations.yaml
  /v2/experimental_staking_undelegate:
    $ref: ./paths/v2/experimental/staking/undelegate.yaml
  /v2/experimental_staking_query_validators:
    $ref: ./paths/v2/experimental/staking/query/validators.yaml
  /v2/experimental_staking_claim_rewards:
    $ref: ./paths/v2/experimental/staking/claim_rewards.yaml
components:
  securitySchemes:
    userpass:
      type: apiKey
      in: header
      name: userpass
      description: "The API key for authentication. Use the 'userpass' value from\
        \ your \nKomodo DeFi Framework instance configuration.\n"
  schemas:
    Common:
      $ref: ./components/schemas/Common.yaml
    Activation:
      $ref: ./components/schemas/Activation.yaml
security:
- userpass: []
