openapi: 3.0.3
info:
  title: Komodo DeFi Framework General API
  version: 2.0.0
  description: 'Focused OpenAPI specification for general endpoints in the Komodo
    DeFi Framework.


    For the complete API specification, see the main openapi.yaml file.'
servers:
- url: /
  description: Local Komodo DeFi Framework instance
tags:
- name: General
  description: Methods for general
paths:
  /v2/sdk-rpc-protocol-v2-0:
    $ref: ./paths/v2/sdk-rpc-protocol-v2-0.yaml
  /v2/coin\_activation:
    $ref: ./paths/v2/coin\_activation.yaml
  /v2/NFT:
    $ref: ./paths/v2/NFT.yaml
  /v2/streaming:
    $ref: ./paths/v2/streaming.yaml
  /v2/swaps\_and\_orders:
    $ref: ./paths/v2/swaps\_and\_orders.yaml
  /v2/Overview:
    $ref: ./paths/v2/Overview.yaml
  /v2/wallet\_methods:
    $ref: ./paths/v2/wallet\_methods.yaml
  /v2/utils:
    $ref: ./paths/v2/utils.yaml
  /v2/enable\_bch\_with\_tokens:
    $ref: ./paths/v2/enable\_bch\_with\_tokens.yaml
  /v2/enable\_tendermint\_token:
    $ref: ./paths/v2/enable\_tendermint\_token.yaml
  /v2/task\_managed\_coin\_activation:
    $ref: ./paths/v2/task\_managed\_coin\_activation.yaml
  /v2/enable\_erc20:
    $ref: ./paths/v2/enable\_erc20.yaml
  /v2/enable\_tendermint\_with\_assets:
    $ref: ./paths/v2/enable\_tendermint\_with\_assets.yaml
  /v2/enable\_eth\_with\_tokens:
    $ref: ./paths/v2/enable\_eth\_with\_tokens.yaml
  /v2/enable\_nft:
    $ref: ./paths/v2/enable\_nft.yaml
  /v2/start\_simple\_market\_maker\_bot:
    $ref: ./paths/v2/start\_simple\_market\_maker\_bot.yaml
  /v2/max\_maker\_vol:
    $ref: ./paths/v2/max\_maker\_vol.yaml
  /v2/best\_orders:
    $ref: ./paths/v2/best\_orders.yaml
  /v2/get\_locked\_amount:
    $ref: ./paths/v2/get\_locked\_amount.yaml
  /v2/orderbook:
    $ref: ./paths/v2/orderbook.yaml
  /v2/my\_recent\_swaps:
    $ref: ./paths/v2/my\_recent\_swaps.yaml
  /v2/active\_swaps:
    $ref: ./paths/v2/active\_swaps.yaml
  /v2/recreate\_swap\_data:
    $ref: ./paths/v2/recreate\_swap\_data.yaml
  /v2/trade\_preimage:
    $ref: ./paths/v2/trade\_preimage.yaml
  /v2/stop\_simple\_market\_maker\_bot:
    $ref: ./paths/v2/stop\_simple\_market\_maker\_bot.yaml
  /v2/tx:
    $ref: ./paths/v2/tx.yaml
  /v2/Fee:
    $ref: ./paths/v2/Fee.yaml
  /v2/get\_wallet\_names:
    $ref: ./paths/v2/get\_wallet\_names.yaml
  /v2/my\_tx\_history:
    $ref: ./paths/v2/my\_tx\_history.yaml
  /v2/sign\_raw\_transaction:
    $ref: ./paths/v2/sign\_raw\_transaction.yaml
  /v2/z\_coin\_tx\_history:
    $ref: ./paths/v2/z\_coin\_tx\_history.yaml
  /v2/withdraw:
    $ref: ./paths/v2/withdraw.yaml
  /v2/get\_raw\_transaction:
    $ref: ./paths/v2/get\_raw\_transaction.yaml
  /v2/set\_swap\_transaction\_fee\_policy:
    $ref: ./paths/v2/set\_swap\_transaction\_fee\_policy.yaml
  /v2/get\_swap\_transaction\_fee\_policy:
    $ref: ./paths/v2/get\_swap\_transaction\_fee\_policy.yaml
  /v2/get\_eth\_estimated\_fee\_per\_gas:
    $ref: ./paths/v2/get\_eth\_estimated\_fee\_per\_gas.yaml
  /v2/get\_enabled\_coins:
    $ref: ./paths/v2/get\_enabled\_coins.yaml
  /v2/get\_current\_mtp:
    $ref: ./paths/v2/get\_current\_mtp.yaml
  /v2/get\_mnemonic:
    $ref: ./paths/v2/get\_mnemonic.yaml
  /v2/message\_signing:
    $ref: ./paths/v2/message\_signing.yaml
  /v2/get\_public\_key:
    $ref: ./paths/v2/get\_public\_key.yaml
  /v2/get\_public\_key\_hash:
    $ref: ./paths/v2/get\_public\_key\_hash.yaml
  /v2/change\_mnemonic\_password:
    $ref: ./paths/v2/change\_mnemonic\_password.yaml
  /v2/remove\_node\_from\_version\_stat:
    $ref: ./paths/v2/remove\_node\_from\_version\_stat.yaml
  /v2/add\_node\_to\_version\_stat:
    $ref: ./paths/v2/add\_node\_to\_version\_stat.yaml
  /v2/update\_version\_stat\_collection:
    $ref: ./paths/v2/update\_version\_stat\_collection.yaml
  /v2/trezor\_initialisation:
    $ref: ./paths/v2/trezor\_initialisation.yaml
  /v2/stop\_version\_stat\_collection:
    $ref: ./paths/v2/stop\_version\_stat\_collection.yaml
  /v2/get\_token\_info:
    $ref: ./paths/v2/get\_token\_info.yaml
  /v2/peer\_connection\_healthcheck:
    $ref: ./paths/v2/peer\_connection\_healthcheck.yaml
  /v2/start\_version\_stat\_collection:
    $ref: ./paths/v2/start\_version\_stat\_collection.yaml
  /v2/sign\_message:
    $ref: ./paths/v2/sign\_message.yaml
  /v2/verify\_message:
    $ref: ./paths/v2/verify\_message.yaml
  /v2/api-rpc-protocol-v2-0-dev:
    $ref: ./paths/v2/api-rpc-protocol-v2-0-dev.yaml
  /v2/get\_token\_allowance:
    $ref: ./paths/v2/get\_token\_allowance.yaml
  /v2/1inch\_v6\_0\_classic\_swap\_liquidity\_sources:
    $ref: ./paths/v2/1inch\_v6\_0\_classic\_swap\_liquidity\_sources.yaml
  /v2/1inch\_v6\_0\_classic\_swap\_create:
    $ref: ./paths/v2/1inch\_v6\_0\_classic\_swap\_create.yaml
  /v2/1inch\_v6\_0\_classic\_swap\_quote:
    $ref: ./paths/v2/1inch\_v6\_0\_classic\_swap\_quote.yaml
  /v2/wc_new_connection:
    $ref: ./paths/v2/wc_new_connection.yaml
  /v2/wc_ping_session:
    $ref: ./paths/v2/wc_ping_session.yaml
  /v2/wc_delete_session:
    $ref: ./paths/v2/wc_delete_session.yaml
  /v2/approve\_token:
    $ref: ./paths/v2/approve\_token.yaml
  /v2/wc_get_sessions:
    $ref: ./paths/v2/wc_get_sessions.yaml
  /v2/wc_get_session:
    $ref: ./paths/v2/wc_get_session.yaml
  /v2/1inch\_v6\_0\_classic\_swap\_tokens:
    $ref: ./paths/v2/1inch\_v6\_0\_classic\_swap\_tokens.yaml
  /v2/common-structures:
    $ref: ./paths/v2/common-structures.yaml
  /v2/nfts-common-structures:
    $ref: ./paths/v2/nfts-common-structures.yaml
  /v2/swaps\_common\_structures:
    $ref: ./paths/v2/swaps\_common\_structures.yaml
  /v2/lightning-common-structures:
    $ref: ./paths/v2/lightning-common-structures.yaml
  /v2/enums:
    $ref: ./paths/v2/enums.yaml
  /v2/wallet\_common\_structures:
    $ref: ./paths/v2/wallet\_common\_structures.yaml
  /v2/activation\_common\_structures:
    $ref: ./paths/v2/activation\_common\_structures.yaml
  /v2/orders\_common\_structures:
    $ref: ./paths/v2/orders\_common\_structures.yaml
  /v2/taker\_events:
    $ref: ./paths/v2/taker\_events.yaml
  /v2/maker\_events:
    $ref: ./paths/v2/maker\_events.yaml
components:
  securitySchemes:
    userpass:
      type: apiKey
      in: header
      name: userpass
      description: "The API key for authentication. Use the 'userpass' value from\
        \ your \nKomodo DeFi Framework instance configuration.\n"
  schemas:
    Common:
      $ref: ./components/schemas/Common.yaml
    Activation:
      $ref: ./components/schemas/Activation.yaml
security:
- userpass: []
