openapi: 3.0.3
info:
  title: Komodo DeFi Framework Lightning API
  version: 2.0.0
  description: 'Focused OpenAPI specification for lightning endpoints in the Komodo
    DeFi Framework.


    For the complete API specification, see the main openapi.yaml file.'
servers:
- url: /
  description: Local Komodo DeFi Framework instance
tags:
- name: Lightning
  description: Methods for lightning
paths:
  /v2/lightning_payments:
    $ref: ./paths/v2/lightning/payments.yaml
  /v2/lightning_activation:
    $ref: ./paths/v2/lightning/activation.yaml
  /v2/lightning_nodes:
    $ref: ./paths/v2/lightning/nodes.yaml
  /v2/lightning_channels:
    $ref: ./paths/v2/lightning/channels.yaml
  /v2/lightning_payments_get\_payment\_details:
    $ref: ./paths/v2/lightning/payments/get\_payment\_details.yaml
  /v2/lightning_payments_send\_payment:
    $ref: ./paths/v2/lightning/payments/send\_payment.yaml
  /v2/lightning_payments_list\_payments\_by\_filter:
    $ref: ./paths/v2/lightning/payments/list\_payments\_by\_filter.yaml
  /v2/lightning_payments_generate\_invoice:
    $ref: ./paths/v2/lightning/payments/generate\_invoice.yaml
  /v2/lightning_nodes_connect\_to\_node:
    $ref: ./paths/v2/lightning/nodes/connect\_to\_node.yaml
  /v2/lightning_nodes_remove\_trusted\_node:
    $ref: ./paths/v2/lightning/nodes/remove\_trusted\_node.yaml
  /v2/lightning_nodes_list\_trusted\_nodes:
    $ref: ./paths/v2/lightning/nodes/list\_trusted\_nodes.yaml
  /v2/lightning_nodes_add\_trusted\_node:
    $ref: ./paths/v2/lightning/nodes/add\_trusted\_node.yaml
  /v2/lightning_channels_close\_channel:
    $ref: ./paths/v2/lightning/channels/close\_channel.yaml
  /v2/lightning_channels_get\_claimable\_balances:
    $ref: ./paths/v2/lightning/channels/get\_claimable\_balances.yaml
  /v2/lightning_channels_get\_channel\_details:
    $ref: ./paths/v2/lightning/channels/get\_channel\_details.yaml
  /v2/lightning_channels_list\_closed\_channels\_by\_filter:
    $ref: ./paths/v2/lightning/channels/list\_closed\_channels\_by\_filter.yaml
  /v2/lightning_channels_update\_channel:
    $ref: ./paths/v2/lightning/channels/update\_channel.yaml
  /v2/lightning_channels_list\_open\_channels\_by\_filter:
    $ref: ./paths/v2/lightning/channels/list\_open\_channels\_by\_filter.yaml
  /v2/lightning_channels_open\_channel:
    $ref: ./paths/v2/lightning/channels/open\_channel.yaml
components:
  securitySchemes:
    userpass:
      type: apiKey
      in: header
      name: userpass
      description: "The API key for authentication. Use the 'userpass' value from\
        \ your \nKomodo DeFi Framework instance configuration.\n"
  schemas:
    Common:
      $ref: ./components/schemas/Common.yaml
    Activation:
      $ref: ./components/schemas/Activation.yaml
security:
- userpass: []
