openapi: 3.0.3
info:
  title: Komodo DeFi Framework API
  version: 2.0.0
  description: 'Complete OpenAPI specification for the Komodo DeFi Framework API.

    This specification covers all available endpoints including coin activation,

    trading, swaps, wallet operations, and more.


    ## Authentication

    All endpoints require authentication using the `userpass` header.


    ## API Versions

    - **v1**: Legacy endpoints (deprecated but still supported)

    - **v2**: Current stable endpoints with enhanced features

    - **v2-dev**: Development endpoints (subject to change)

    '
  x-last-updated: '2025-06-08T16:58:39.225391'
  x-updated-by: mapping.py script
servers:
- url: /
  description: Local Komodo DeFi Framework instance
tags:
- name: Coin Activation
  description: Methods for activating and managing coins and tokens
- name: Trading & Orders
  description: Trading operations, order management, and market making
- name: Atomic Swaps
  description: Cross-chain atomic swap operations
- name: Wallet Management
  description: Wallet operations including balance, transactions, and staking
- name: Lightning Network
  description: Lightning Network operations and channel management
- name: NFTs
  description: Non-Fungible Token operations
- name: Streaming
  description: Real-time data streaming endpoints
- name: Utilities
  description: Utility functions and system operations
- name: Legacy (v1)
  description: Legacy v1 endpoints (deprecated)
paths:
  /v1/active_swaps:
    $ref: ./paths/v1/active_swaps.yaml
  /v1/all_swaps_uuids_by_filter:
    $ref: ./paths/v1/all_swaps_uuids_by_filter.yaml
  /v1/ban_pubkey:
    $ref: ./paths/v1/ban_pubkey.yaml
  /v1/best_orders:
    $ref: ./paths/v1/best_orders.yaml
  /v1/buy:
    $ref: ./paths/v1/buy.yaml
  /v1/cancel_all_orders:
    $ref: ./paths/v1/cancel_all_orders.yaml
  /v1/cancel_order:
    $ref: ./paths/v1/cancel_order.yaml
  /v1/coins_needed_for_kick_start:
    $ref: ./paths/v1/coins_needed_for_kick_start.yaml
  /v1/convert_utxo_address:
    $ref: ./paths/v1/convert_utxo_address.yaml
  /v1/convertaddress:
    $ref: ./paths/v1/convertaddress.yaml
  /v1/disable_coin:
    $ref: ./paths/v1/disable_coin.yaml
  /v1/electrum:
    $ref: ./paths/v1/electrum.yaml
  /v1/enable:
    $ref: ./paths/v1/enable.yaml
  /v1/get_directly_connected_peers:
    $ref: ./paths/v1/get_directly_connected_peers.yaml
  /v1/get_enabled_coins:
    $ref: ./paths/v1/get_enabled_coins.yaml
  /v1/get_gossip_mesh:
    $ref: ./paths/v1/get_gossip_mesh.yaml
  /v1/get_gossip_peer_topics:
    $ref: ./paths/v1/get_gossip_peer_topics.yaml
  /v1/get_gossip_topic_peers:
    $ref: ./paths/v1/get_gossip_topic_peers.yaml
  /v1/get_my_peer_id:
    $ref: ./paths/v1/get_my_peer_id.yaml
  /v1/get_relay_mesh:
    $ref: ./paths/v1/get_relay_mesh.yaml
  /v1/get_trade_fee:
    $ref: ./paths/v1/get_trade_fee.yaml
  /v1/import_swaps:
    $ref: ./paths/v1/import_swaps.yaml
  /v1/kmd_rewards_info:
    $ref: ./paths/v1/kmd_rewards_info.yaml
  /v1/list_banned_pubkeys:
    $ref: ./paths/v1/list_banned_pubkeys.yaml
  /v1/max_taker_vol:
    $ref: ./paths/v1/max_taker_vol.yaml
  /v1/metrics:
    $ref: ./paths/v1/metrics.yaml
  /v1/min_trading_vol:
    $ref: ./paths/v1/min_trading_vol.yaml
  /v1/my_balance:
    $ref: ./paths/v1/my_balance.yaml
  /v1/my_orders:
    $ref: ./paths/v1/my_orders.yaml
  /v1/my_recent_swaps:
    $ref: ./paths/v1/my_recent_swaps.yaml
  /v1/my_swap_status:
    $ref: ./paths/v1/my_swap_status.yaml
  /v1/my_tx_history:
    $ref: ./paths/v1/my_tx_history.yaml
  /v1/order_status:
    $ref: ./paths/v1/order_status.yaml
  /v1/orderbook:
    $ref: ./paths/v1/orderbook.yaml
  /v1/orderbook_depth:
    $ref: ./paths/v1/orderbook_depth.yaml
  /v1/orders_history_by_filter:
    $ref: ./paths/v1/orders_history_by_filter.yaml
  /v1/recover_funds_of_swap:
    $ref: ./paths/v1/recover_funds_of_swap.yaml
  /v1/sell:
    $ref: ./paths/v1/sell.yaml
  /v1/send_raw_transaction:
    $ref: ./paths/v1/send_raw_transaction.yaml
  /v1/set_required_confirmations:
    $ref: ./paths/v1/set_required_confirmations.yaml
  /v1/set_requires_notarization:
    $ref: ./paths/v1/set_requires_notarization.yaml
  /v1/setprice:
    $ref: ./paths/v1/setprice.yaml
  /v1/show_priv_key:
    $ref: ./paths/v1/show_priv_key.yaml
  /v1/trade_preimage:
    $ref: ./paths/v1/trade_preimage.yaml
  /v1/unban_pubkeys:
    $ref: ./paths/v1/unban_pubkeys.yaml
  /v1/update_maker_order:
    $ref: ./paths/v1/update_maker_order.yaml
  /v1/validateaddress:
    $ref: ./paths/v1/validateaddress.yaml
  /v1/version:
    $ref: ./paths/v1/version.yaml
  /v1/withdraw:
    $ref: ./paths/v1/withdraw.yaml
  /v2/1inch_v6_0_classic_swap_create:
    $ref: ./paths/v2/1inch_v6_0_classic_swap_create.yaml
  /v2/1inch_v6_0_classic_swap_liquidity_sources:
    $ref: ./paths/v2/1inch_v6_0_classic_swap_liquidity_sources.yaml
  /v2/1inch_v6_0_classic_swap_quote:
    $ref: ./paths/v2/1inch_v6_0_classic_swap_quote.yaml
  /v2/1inch_v6_0_classic_swap_tokens:
    $ref: ./paths/v2/1inch_v6_0_classic_swap_tokens.yaml
  /v2/active_swaps:
    $ref: ./paths/v2/active_swaps.yaml
  /v2/add_delegation:
    $ref: ./paths/v2/add_delegation.yaml
  /v2/add_node_to_version_stat:
    $ref: ./paths/v2/add_node_to_version_stat.yaml
  /v2/approve_token:
    $ref: ./paths/v2/approve_token.yaml
  /v2/best_orders:
    $ref: ./paths/v2/best_orders.yaml
  /v2/change_mnemonic_password:
    $ref: ./paths/v2/change_mnemonic_password.yaml
  /v2/clear_nft_db:
    $ref: ./paths/v2/clear_nft_db.yaml
  /v2/disable:
    $ref: ./paths/v2/disable.yaml
  /v2/enable_bch_with_tokens:
    $ref: ./paths/v2/enable_bch_with_tokens.yaml
  /v2/enable_erc20:
    $ref: ./paths/v2/enable_erc20.yaml
  /v2/enable_eth_with_tokens:
    $ref: ./paths/v2/enable_eth_with_tokens.yaml
  /v2/enable_nft:
    $ref: ./paths/v2/enable_nft.yaml
  /v2/enable_slp:
    $ref: ./paths/v2/enable_slp.yaml
  /v2/enable_tendermint_token:
    $ref: ./paths/v2/enable_tendermint_token.yaml
  /v2/enable_tendermint_with_assets:
    $ref: ./paths/v2/enable_tendermint_with_assets.yaml
  /v2/get_current_mtp:
    $ref: ./paths/v2/get_current_mtp.yaml
  /v2/get_enabled_coins:
    $ref: ./paths/v2/get_enabled_coins.yaml
  /v2/get_eth_estimated_fee_per_gas:
    $ref: ./paths/v2/get_eth_estimated_fee_per_gas.yaml
  /v2/get_locked_amount:
    $ref: ./paths/v2/get_locked_amount.yaml
  /v2/get_mnemonic:
    $ref: ./paths/v2/get_mnemonic.yaml
  /v2/get_nft_list:
    $ref: ./paths/v2/get_nft_list.yaml
  /v2/get_nft_metadata:
    $ref: ./paths/v2/get_nft_metadata.yaml
  /v2/get_nft_transfers:
    $ref: ./paths/v2/get_nft_transfers.yaml
  /v2/get_public_key:
    $ref: ./paths/v2/get_public_key.yaml
  /v2/get_public_key_hash:
    $ref: ./paths/v2/get_public_key_hash.yaml
  /v2/get_raw_transaction:
    $ref: ./paths/v2/get_raw_transaction.yaml
  /v2/get_staking_infos:
    $ref: ./paths/v2/get_staking_infos.yaml
  /v2/get_swap_transaction_fee_policy:
    $ref: ./paths/v2/get_swap_transaction_fee_policy.yaml
  /v2/get_token_allowance:
    $ref: ./paths/v2/get_token_allowance.yaml
  /v2/get_token_info:
    $ref: ./paths/v2/get_token_info.yaml
  /v2/get_wallet_names:
    $ref: ./paths/v2/get_wallet_names.yaml
  /v2/lightning-channels-close_channel:
    $ref: ./paths/v2/lightning-channels-close_channel.yaml
  /v2/lightning-channels-get_channel_details:
    $ref: ./paths/v2/lightning-channels-get_channel_details.yaml
  /v2/lightning-channels-get_claimable_balances:
    $ref: ./paths/v2/lightning-channels-get_claimable_balances.yaml
  /v2/lightning-channels-list_closed_channels_by_filter:
    $ref: ./paths/v2/lightning-channels-list_closed_channels_by_filter.yaml
  /v2/lightning-channels-list_open_channels_by_filter:
    $ref: ./paths/v2/lightning-channels-list_open_channels_by_filter.yaml
  /v2/lightning-channels-open_channel:
    $ref: ./paths/v2/lightning-channels-open_channel.yaml
  /v2/lightning-channels-update_channel:
    $ref: ./paths/v2/lightning-channels-update_channel.yaml
  /v2/lightning-nodes-add_trusted_node:
    $ref: ./paths/v2/lightning-nodes-add_trusted_node.yaml
  /v2/lightning-nodes-connect_to_node:
    $ref: ./paths/v2/lightning-nodes-connect_to_node.yaml
  /v2/lightning-nodes-list_trusted_nodes:
    $ref: ./paths/v2/lightning-nodes-list_trusted_nodes.yaml
  /v2/lightning-nodes-remove_trusted_node:
    $ref: ./paths/v2/lightning-nodes-remove_trusted_node.yaml
  /v2/lightning-payments-generate_invoice:
    $ref: ./paths/v2/lightning-payments-generate_invoice.yaml
  /v2/lightning-payments-get_payment_details:
    $ref: ./paths/v2/lightning-payments-get_payment_details.yaml
  /v2/lightning-payments-list_payments_by_filter:
    $ref: ./paths/v2/lightning-payments-list_payments_by_filter.yaml
  /v2/lightning-payments-send_payment:
    $ref: ./paths/v2/lightning-payments-send_payment.yaml
  /v2/max_maker_vol:
    $ref: ./paths/v2/max_maker_vol.yaml
  /v2/my_recent_swaps:
    $ref: ./paths/v2/my_recent_swaps.yaml
  /v2/my_tx_history:
    $ref: ./paths/v2/my_tx_history.yaml
  /v2/orderbook:
    $ref: ./paths/v2/orderbook.yaml
  /v2/peer_connection_healthcheck:
    $ref: ./paths/v2/peer_connection_healthcheck.yaml
  /v2/recreate_swap_data:
    $ref: ./paths/v2/recreate_swap_data.yaml
  /v2/refresh_nft_metadata:
    $ref: ./paths/v2/refresh_nft_metadata.yaml
  /v2/remove_delegation:
    $ref: ./paths/v2/remove_delegation.yaml
  /v2/remove_node_from_version_stat:
    $ref: ./paths/v2/remove_node_from_version_stat.yaml
  /v2/set_swap_transaction_fee_policy:
    $ref: ./paths/v2/set_swap_transaction_fee_policy.yaml
  /v2/sign_message:
    $ref: ./paths/v2/sign_message.yaml
  /v2/sign_raw_transaction:
    $ref: ./paths/v2/sign_raw_transaction.yaml
  /v2/start_simple_market_maker_bot:
    $ref: ./paths/v2/start_simple_market_maker_bot.yaml
  /v2/start_version_stat_collection:
    $ref: ./paths/v2/start_version_stat_collection.yaml
  /v2/stop_simple_market_maker_bot:
    $ref: ./paths/v2/stop_simple_market_maker_bot.yaml
  /v2/stop_version_stat_collection:
    $ref: ./paths/v2/stop_version_stat_collection.yaml
  /v2/stream-balance-enable:
    $ref: ./paths/v2/stream-balance-enable.yaml
  /v2/stream-disable:
    $ref: ./paths/v2/stream-disable.yaml
  /v2/stream-fee_estimator-enable:
    $ref: ./paths/v2/stream-fee_estimator-enable.yaml
  /v2/stream-heartbeat-enable:
    $ref: ./paths/v2/stream-heartbeat-enable.yaml
  /v2/stream-network-enable:
    $ref: ./paths/v2/stream-network-enable.yaml
  /v2/stream-order_status-enable:
    $ref: ./paths/v2/stream-order_status-enable.yaml
  /v2/stream-orderbook-enable:
    $ref: ./paths/v2/stream-orderbook-enable.yaml
  /v2/stream-swap_status-enable:
    $ref: ./paths/v2/stream-swap_status-enable.yaml
  /v2/stream-tx_history-enable:
    $ref: ./paths/v2/stream-tx_history-enable.yaml
  /v2/task-account_balance-cancel:
    $ref: ./paths/v2/task-account_balance-cancel.yaml
  /v2/task-account_balance-init:
    $ref: ./paths/v2/task-account_balance-init.yaml
  /v2/task-account_balance-status:
    $ref: ./paths/v2/task-account_balance-status.yaml
  /v2/task-create_new_account-init:
    $ref: ./paths/v2/task-create_new_account-init.yaml
  /v2/task-create_new_account-status:
    $ref: ./paths/v2/task-create_new_account-status.yaml
  /v2/task-enable_bch-cancel:
    $ref: ./paths/v2/task-enable_bch-cancel.yaml
  /v2/task-enable_bch-init:
    $ref: ./paths/v2/task-enable_bch-init.yaml
  /v2/task-enable_bch-status:
    $ref: ./paths/v2/task-enable_bch-status.yaml
  /v2/task-enable_bch-user_action:
    $ref: ./paths/v2/task-enable_bch-user_action.yaml
  /v2/task-enable_eth-cancel:
    $ref: ./paths/v2/task-enable_eth-cancel.yaml
  /v2/task-enable_eth-init:
    $ref: ./paths/v2/task-enable_eth-init.yaml
  /v2/task-enable_eth-status:
    $ref: ./paths/v2/task-enable_eth-status.yaml
  /v2/task-enable_eth-user_action:
    $ref: ./paths/v2/task-enable_eth-user_action.yaml
  /v2/task-enable_lightning-cancel:
    $ref: ./paths/v2/task-enable_lightning-cancel.yaml
  /v2/task-enable_lightning-init:
    $ref: ./paths/v2/task-enable_lightning-init.yaml
  /v2/task-enable_lightning-status:
    $ref: ./paths/v2/task-enable_lightning-status.yaml
  /v2/task-enable_qtum-cancel:
    $ref: ./paths/v2/task-enable_qtum-cancel.yaml
  /v2/task-enable_qtum-init:
    $ref: ./paths/v2/task-enable_qtum-init.yaml
  /v2/task-enable_qtum-status:
    $ref: ./paths/v2/task-enable_qtum-status.yaml
  /v2/task-enable_qtum-user_action:
    $ref: ./paths/v2/task-enable_qtum-user_action.yaml
  /v2/task-enable_tendermint-cancel:
    $ref: ./paths/v2/task-enable_tendermint-cancel.yaml
  /v2/task-enable_tendermint-init:
    $ref: ./paths/v2/task-enable_tendermint-init.yaml
  /v2/task-enable_tendermint-status:
    $ref: ./paths/v2/task-enable_tendermint-status.yaml
  /v2/task-enable_tendermint-user_action:
    $ref: ./paths/v2/task-enable_tendermint-user_action.yaml
  /v2/task-enable_utxo-cancel:
    $ref: ./paths/v2/task-enable_utxo-cancel.yaml
  /v2/task-enable_utxo-init:
    $ref: ./paths/v2/task-enable_utxo-init.yaml
  /v2/task-enable_utxo-status:
    $ref: ./paths/v2/task-enable_utxo-status.yaml
  /v2/task-enable_utxo-user_action:
    $ref: ./paths/v2/task-enable_utxo-user_action.yaml
  /v2/task-enable_z_coin-cancel:
    $ref: ./paths/v2/task-enable_z_coin-cancel.yaml
  /v2/task-enable_z_coin-init:
    $ref: ./paths/v2/task-enable_z_coin-init.yaml
  /v2/task-enable_z_coin-status:
    $ref: ./paths/v2/task-enable_z_coin-status.yaml
  /v2/task-enable_z_coin-user_action:
    $ref: ./paths/v2/task-enable_z_coin-user_action.yaml
  /v2/task-get_new_address-cancel:
    $ref: ./paths/v2/task-get_new_address-cancel.yaml
  /v2/task-get_new_address-init:
    $ref: ./paths/v2/task-get_new_address-init.yaml
  /v2/task-get_new_address-status:
    $ref: ./paths/v2/task-get_new_address-status.yaml
  /v2/task-get_new_address-user_action:
    $ref: ./paths/v2/task-get_new_address-user_action.yaml
  /v2/task-init_trezor-cancel:
    $ref: ./paths/v2/task-init_trezor-cancel.yaml
  /v2/task-init_trezor-init:
    $ref: ./paths/v2/task-init_trezor-init.yaml
  /v2/task-init_trezor-status:
    $ref: ./paths/v2/task-init_trezor-status.yaml
  /v2/task-init_trezor-user_action:
    $ref: ./paths/v2/task-init_trezor-user_action.yaml
  /v2/task-scan_for_new_addresses-init:
    $ref: ./paths/v2/task-scan_for_new_addresses-init.yaml
  /v2/task-scan_for_new_addresses-status:
    $ref: ./paths/v2/task-scan_for_new_addresses-status.yaml
  /v2/task-withdraw-cancel:
    $ref: ./paths/v2/task-withdraw-cancel.yaml
  /v2/task-withdraw-init:
    $ref: ./paths/v2/task-withdraw-init.yaml
  /v2/task-withdraw-status:
    $ref: ./paths/v2/task-withdraw-status.yaml
  /v2/trade_preimage:
    $ref: ./paths/v2/trade_preimage.yaml
  /v2/update_nft:
    $ref: ./paths/v2/update_nft.yaml
  /v2/update_version_stat_collection:
    $ref: ./paths/v2/update_version_stat_collection.yaml
  /v2/verify_message:
    $ref: ./paths/v2/verify_message.yaml
  /v2/withdraw:
    $ref: ./paths/v2/withdraw.yaml
  /v2/withdraw_nft:
    $ref: ./paths/v2/withdraw_nft.yaml
  /v2/z_coin_tx_history:
    $ref: ./paths/v2/z_coin_tx_history.yaml
components:
  securitySchemes:
    userpass:
      type: apiKey
      in: header
      name: userpass
      description: "The API key for authentication. Use the 'userpass' value from your \nKomodo DeFi Framework instance configuration.\n"
  schemas:
    Activation:
      $ref: ./components/schemas/Activation.yaml
    Lightning:
      $ref: ./components/schemas/Lightning.yaml
    Nfts:
      $ref: ./components/schemas/Nfts.yaml
    Orders:
      $ref: ./components/schemas/Orders.yaml
    Swaps:
      $ref: ./components/schemas/Swaps.yaml
    MakerEvents:
      $ref: ./components/schemas/MakerEvents.yaml
    TakerEvents:
      $ref: ./components/schemas/TakerEvents.yaml
    Wallet:
      $ref: ./components/schemas/Wallet.yaml
    BotConfig:
      $ref: ./components/schemas/BotConfig.yaml
    Common:
      $ref: ./components/schemas/Common.yaml
security:
- userpass: []
