openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Activation Common Structures API
  version: v2
  description: OpenAPI specification for the activation_common_structures methods.
paths:
  /activation_common_structures:
    post:
      summary: 'Komodo DeFi SDK Common Structures: Activation'
      description: The Komodo DeFi SDK uses a variety of activation methods, depending
        on the type of coin.
      operationId: activation_common_structures
      tags:
      - activation_common_structures
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - activation_common_structures
      responses:
        '200':
          description: Successful response for activation_common_structures
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/activation_common_structures_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
