openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Approve Token V2 API
  version: v2
  description: OpenAPI specification for the approve_token_v2 methods.
paths:
  /approve_token:
    post:
      summary: Approve Token (v2)
      description: Method description for approve_token
      operationId: approve_token
      tags:
      - approve_token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - approve_token
      responses:
        '200':
          description: Successful response for approve_token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/approve_token_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
