openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Cancel Order API
  version: v2
  description: OpenAPI specification for the cancel_order methods.
paths:
  /cancel_order:
    post:
      summary: Cancel Order
      description: The cancel_order cancels the active order created by the Komodo
        DeFi Framework API node.
      operationId: cancel_order
      tags:
      - cancel_order
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - cancel_order
      responses:
        '200':
          description: Successful response for cancel_order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cancel_order_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
