openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Change Mnemonic Password API
  version: v2
  description: OpenAPI specification for the change_mnemonic_password methods.
paths:
  /change_mnemonic_password:
    post:
      summary: Change Mnemonic Password
      description: The change_mnemonic_password method allows a user to update the
        password used to encrypt a mnemonic phrase in their local database.
      operationId: change_mnemonic_password
      tags:
      - change_mnemonic_password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - change_mnemonic_password
                params:
                  type: object
                  properties:
                    current_password:
                      description: the active mnemonic password for your wallet
                      type: string
                    new_password:
                      description: the new password to use for encrypting your active
                        mnemonic password
                      type: string
                  required:
                  - current_password
                  - new_password
      responses:
        '200':
          description: Successful response for change_mnemonic_password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/change_mnemonic_password_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
