openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Enable Tendermint With Assets API
  version: v2
  description: OpenAPI specification for the enable_tendermint_with_assets methods.
paths:
  /enable_tendermint_with_assets:
    post:
      summary: Enable Tendermint Token with Assets
      description: Use this method to activate Tendermint coins (COSMOS/IRIS/OSMOSIS)
        and IBC assets in a single command.
      operationId: enable_tendermint_with_assets
      tags:
      - enable_tendermint_with_assets
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - enable_tendermint_with_assets
      responses:
        '200':
          description: Successful response for enable_tendermint_with_assets
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/enable_tendermint_with_assets_Response'
              example:
                mmrpc: '2.0'
                result:
                  address: string_value
                  balance: {}
                  current_block: 123
                  ticker: string_value
                  tokens_balances: {}
                  tokens_tickers: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
