openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Get Nft List V2 API
  version: v2
  description: OpenAPI specification for the get_nft_list_v2 methods.
paths:
  /get_nft_list:
    post:
      summary: Get NFT List
      description: The get_nft_list method returns a list of NFTs owned by the user,
        with support for filtering, pagination, and spam protection.
      operationId: get_nft_list
      tags:
      - get_nft_list
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - get_nft_list
      responses:
        '200':
          description: Successful response for get_nft_list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_nft_list_Response'
              example:
                mmrpc: '2.0'
                result:
                  nfts: {}
                  skipped: 123
                  total: 123
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
