openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Get Current Mtp V2 API
  version: v2
  description: OpenAPI specification for the get_current_mtp_v2 methods.
paths:
  /get_current_mtp:
    post:
      summary: Get Current MTP
      description: The get_current_mtp method returns the Median Time Past (MTP) from
        electrum servers for UTXO coins.
      operationId: get_current_mtp
      tags:
      - get_current_mtp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - get_current_mtp
                params:
                  type: object
                  properties:
                    coin:
                      description: A compatible (UTXO) coin's ticker
                      type: string
                      default: '`-`'
                    id:
                      description: Optional. Identifies a request to allow matching
                        it with a response. Defaults to `null`
                      type: integer
                      default: '`null`'
                  required:
                  - coin
      responses:
        '200':
          description: Successful response for get_current_mtp
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_current_mtp_Response'
              example:
                mmrpc: '2.0'
                result:
                  mtp: 123
                  id: 123
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
