openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Get Token Allowance V2 API
  version: v2
  description: OpenAPI specification for the get_token_allowance_v2 methods.
paths:
  /get_token_allowance:
    post:
      summary: Get Token Allowance
      description: Method description for get_token_allowance
      operationId: get_token_allowance
      tags:
      - get_token_allowance
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - get_token_allowance
      responses:
        '200':
          description: Successful response for get_token_allowance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_token_allowance_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
