openapi: 3.0.0
info:
  title: Komodo DeFi Framework - My Orders API
  version: v2
  description: OpenAPI specification for the my_orders methods.
paths:
  /my_orders:
    post:
      summary: My Orders
      description: The my_orders method returns the data of all active orders created
        by the Komodo DeFi Framework API node.
      operationId: my_orders
      tags:
      - my_orders
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - my_orders
      responses:
        '200':
          description: Successful response for my_orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/my_orders_Response'
              example:
                mmrpc: '2.0'
                result:
                  maker_orders: {}
                  taker_orders: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
