openapi: 3.0.0
info:
  title: Komodo DeFi Framework - My Tx History V2 API
  version: v2
  description: OpenAPI specification for the my_tx_history_v2 methods.
paths:
  /my_tx_history:
    post:
      summary: My TX History
      description: The my_tx_history method allows you to view the transaction history
        of coins.
      operationId: my_tx_history
      tags:
      - my_tx_history
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - my_tx_history
                params:
                  type: object
                  properties:
                    coin:
                      description: Ticker of the coin to get history for.
                      type: string
                      default: '-'
                    limit:
                      description: Limits the number of returned transactions. Defaults
                        to `10`. Ignored if `max = true`.
                      type: integer
                      default: '`10`'
                    paging_options:
                      description: A standard [Pagination](/komodo-defi-framework/api/common_structures/#pagination)
                        object.
                      type: object
                      default: '-'
                    target:
                      description: A standard [HistoryTarget](/komodo-defi-framework/api/common_structures/wallet/#history-target)
                        object.
                      type: object
                      default: '-'
                  required:
                  - coin
      responses:
        '200':
          description: Successful response for my_tx_history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/my_tx_history_Response'
              example:
                mmrpc: '2.0'
                result:
                  current_block: {}
                  from_id: string_value
                  limit: {}
                  page_number: {}
                  skipped: {}
                  sync_status: {}
                  total: {}
                  total_pages: {}
                  transactions: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
