openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Nft API
  version: v2
  description: OpenAPI specification for the NFT methods.
paths:
  /NFT:
    post:
      summary: 'Komodo DeFi Framework Method Overview: Non-Fungible Tokens'
      description: This document provides an overview of all methods Komodo DeFi Framework
        offers to interact with NFTs.
      operationId: NFT
      tags:
      - NFT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - NFT
      responses:
        '200':
          description: Successful response for NFT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NFT_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
