openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Remove Node From Version Stat API
  version: v2
  description: OpenAPI specification for the remove_node_from_version_stat methods.
paths:
  /remove_node_from_version_stat:
    post:
      summary: Remove Node from Version Stat
      description: Removes a node from the local version stat database in Komodo DeFi
        Framework.
      operationId: remove_node_from_version_stat
      tags:
      - remove_node_from_version_stat
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - remove_node_from_version_stat
                params:
                  type: object
                  properties:
                    name:
                      description: The name assigned to the node
                      type: string
                  required:
                  - name
      responses:
        '200':
          description: Successful response for remove_node_from_version_stat
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/remove_node_from_version_stat_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
