openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Sign Message API
  version: v2
  description: OpenAPI specification for the sign_message methods.
paths:
  /sign_message:
    post:
      summary: Sign Message
      description: The method in this document allows you to sign messages for all
        coins supported by Komodo DeFi Framework.
      operationId: sign_message
      tags:
      - sign_message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - sign_message
                params:
                  type: object
                  properties:
                    address:
                      description: HD wallets only. A standard [AddressPath](/komodo-defi-framework/api/common_structures/wallet/#address-path)
                        object. The path to the address for signing the message. If
                        not provided, the `account_id`, `chain`, and `address_id`
                        will default to `0`.
                      type: string
                      default: '`0`'
                    coin:
                      description: The coin to sign a message with.
                      type: string
                      default: '`-`'
                    message:
                      description: The message you want to sign.
                      type: string
                      default: '`-`'
                  required:
                  - coin
                  - message
      responses:
        '200':
          description: Successful response for sign_message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sign_message_Response'
              example:
                mmrpc: '2.0'
                result:
                  signature: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
