openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Start Simple Market Maker Bot V2 API
  version: v2
  description: OpenAPI specification for the start_simple_market_maker_bot_v2 methods.
paths:
  /start_simple_market_maker_bot:
    post:
      summary: start_simple_market_maker_bot
      description: Method description for start_simple_market_maker_bot
      operationId: start_simple_market_maker_bot
      tags:
      - start_simple_market_maker_bot
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - start_simple_market_maker_bot
                params:
                  type: object
                  properties:
                    bot_refresh_rate:
                      description: Bot loop interval in seconds
                      type: number
                      default: '`30`'
                    cfg.name.base:
                      description: Ticker of the coin you wish to sell
                      type: string
                      default: '`-`'
                    cfg.name.base_confs:
                      description: Number of required blockchain confirmations for
                        base coin atomic swap transaction; defaults to base coin configuration
                        if not set
                      type: integer
                      default: '`-`'
                    cfg.name.base_nota:
                      description: Whether dPoW notarization is required for base
                        coin atomic swap transaction; defaults to base coin configuration
                        if not set
                      type: boolean
                      default: '`-`'
                    cfg.name.check_last_bidirectional_trade_thresh_hold:
                      description: Will readjust the calculated cex price if a precedent
                        trade exists for the pair (or reversed pair), applied via
                        a [VWAP logic](https://www.investopedia.com/terms/v/vwap.asp)
                      type: boolean
                      default: '`false`'
                    cfg.name.enable:
                      description: Bot will ignore this config entry if set to false
                      type: boolean
                      default: '`-`'
                    cfg.name.max:
                      description: Set to `true` if you would like to trade your whole
                        balance
                      type: boolean
                      default: '`-`'
                    cfg.name.max_volume.percentage:
                      description: Percentage of balance to trade (cannot use at same
                        time as `max_volume.usd`; if greater than 1.0 `max=true` is
                        implied)
                      type: string
                      default: '`-`'
                    cfg.name.max_volume.usd:
                      description: Maximum USD trade volume value to trade (cannot
                        use at same time as `max_volume.percentage`; if greater than
                        full balance `max=true` is implied)
                      type: string
                      default: '`-`'
                    cfg.name.min_base_price:
                      description: Minimum USD price of base coin to accept in trade
                      type: number
                      default: '`-`'
                    cfg.name.min_pair_price:
                      description: Minimum USD price of pair (base/rel) to accept
                        in trade
                      type: number
                      default: '`-`'
                    cfg.name.min_rel_price:
                      description: Minimum USD price of rel coin to accept in trade
                      type: number
                      default: '`-`'
                    cfg.name.min_volume.percentage:
                      description: Minimum percentage of balance to accept in trade
                        (cannot use at same time as `min_volume.usd`)
                      type: string
                      default: '`-`'
                    cfg.name.min_volume.usd:
                      description: Minimum USD trade volume of trades accepted for
                        order (cannot use at same time as `min_volume.percentage`)
                      type: number
                      default: '`-`'
                    cfg.name.name:
                      description: The name assigned to this configuration (e.g. the
                        pair being configured)
                      type: string
                      default: '`-`'
                    cfg.name.price_elapsed_validity:
                      description: Will cancel current orders for this pair and not
                        submit a new order if last price update time has been longer
                        than this value in seconds
                      type: number
                      default: '`300`'
                    cfg.name.rel:
                      description: Ticker of the coin you wish to buy
                      type: string
                      default: '`-`'
                    cfg.name.rel_confs:
                      description: Number of required blockchain confirmations for
                        rel coin atomic swap transaction; defaults to rel coin configuration
                        if not set
                      type: integer
                      default: '`-`'
                    cfg.name.rel_nota:
                      description: Whether dPoW notarization is required for rel coin
                        atomic swap transaction; defaults to base coin configuration
                        if not set
                      type: boolean
                      default: '`-`'
                    cfg.name.spread:
                      description: Target price in relation to prices API value
                      type: string
                      default: '`-`'
                    price_urls:
                      description: A list of URLs serving price data in JSON format.
                        During each update loop, price data will be sourced from the
                        first working URL in the list. If not defined, a [default
                        list](https://github.com/KomodoPlatform/komodo-defi-framework/blob/main/mm2src/coins/lp_price.rs#L13)
                        will be used.
                      type: string
                      default: '`-`'
                  required:
                  - cfg.name.base
                  - cfg.name.enable
                  - cfg.name.name
                  - cfg.name.rel
                  - cfg.name.spread
      responses:
        '200':
          description: Successful response for start_simple_market_maker_bot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/start_simple_market_maker_bot_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
