openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Start Version Stat Collection API
  version: v2
  description: OpenAPI specification for the start_version_stat_collection methods.
paths:
  /start_version_stat_collection:
    post:
      summary: Start Version Stat Collection
      description: The start_version_stat_collection method initiates storing version
        statistics for nodes previously registered via the add_node_to_version_stat
        method.
      operationId: start_version_stat_collection
      tags:
      - start_version_stat_collection
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - start_version_stat_collection
                params:
                  type: object
                  properties:
                    interval:
                      description: polling rate (in seconds) to check node versions
                      type: integer
                  required:
                  - interval
      responses:
        '200':
          description: Successful response for start_version_stat_collection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/start_version_stat_collection_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
