openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Stop Simple Market Maker Bot V2 API
  version: v2
  description: OpenAPI specification for the stop_simple_market_maker_bot_v2 methods.
paths:
  /stop_simple_market_maker_bot:
    post:
      summary: Stop Simple Market Maker Bot
      description: The stop_simple_market_maker_bot method tells the bot to finish
        placing orders at the end of the current loop 30 seconds minimum and 30 seconds
        by default.
      operationId: stop_simple_market_maker_bot
      tags:
      - stop_simple_market_maker_bot
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - stop_simple_market_maker_bot
      responses:
        '200':
          description: Successful response for stop_simple_market_maker_bot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stop_simple_market_maker_bot_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
