openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Streaming API
  version: v2
  description: OpenAPI specification for the streaming methods.
paths:
  /streaming:
    post:
      summary: 'Komodo DeFi Framework Method Overview: Streaming Methods'
      description: This document provides an overview of methods to configure and
        initiate the KDF streaming interface.
      operationId: streaming
      tags:
      - streaming
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - streaming
      responses:
        '200':
          description: Successful response for streaming
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/streaming_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
