openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Task Managed Coin Activation API
  version: v2
  description: OpenAPI specification for the task_managed_coin_activation methods.
paths:
  /task_managed_coin_activation:
    post:
      summary: 'Komodo DeFi Framework Method Overview: Task Managed Coin Activation'
      description: This document provides an overview of task managed coin activation
        methods in the Komodo DeFi Framework API.
      operationId: task_managed_coin_activation
      tags:
      - task_managed_coin_activation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task_managed_coin_activation
      responses:
        '200':
          description: Successful response for task_managed_coin_activation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_managed_coin_activation_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
