openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Trezor Initialisation API
  version: v2
  description: OpenAPI specification for the trezor_initialisation methods.
paths:
  /trezor_initialisation:
    post:
      summary: 'Komodo DeFi Framework Method Overview: Trezor Initialization'
      description: This document provides an overview of Trezor initialization methods
        available in the Komodo DeFi Framework.
      operationId: trezor_initialisation
      tags:
      - trezor_initialisation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - trezor_initialisation
      responses:
        '200':
          description: Successful response for trezor_initialisation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/trezor_initialisation_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
