openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Update Nft V2 API
  version: v2
  description: OpenAPI specification for the update_nft_v2 methods.
paths:
  /update_nft:
    post:
      summary: Update NFT
      description: Method description for update_nft
      operationId: update_nft
      tags:
      - update_nft
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - update_nft
      responses:
        '200':
          description: Successful response for update_nft
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/update_nft_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
