openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Wc Get Session V2 API
  version: v2
  description: OpenAPI specification for the wc_get_session_v2 methods.
paths:
  /wc_get_session:
    post:
      summary: 'Walletconnect: Get session'
      description: Method description for wc_get_session
      operationId: wc_get_session
      tags:
      - wc_get_session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - wc_get_session
      responses:
        '200':
          description: Successful response for wc_get_session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wc_get_session_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
