openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Withdraw Nft API
  version: v2
  description: OpenAPI specification for the withdraw_nft methods.
paths:
  /withdraw_nft:
    post:
      summary: Withdraw NFT
      description: The withdraw_nft method creates a signed transaction to withdraw
        an NFT, supporting both ERC721 and ERC1155 types.
      operationId: withdraw_nft
      tags:
      - withdraw_nft
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - withdraw_nft
      responses:
        '200':
          description: Successful response for withdraw_nft
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/withdraw_nft_Response'
              example:
                mmrpc: '2.0'
                result:
                  amount: string_value
                  block_height: 123
                  coin: string_value
                  contract_type: string_value
                  fee_details: {}
                  from: {}
                  internal_id: 123
                  timestamp: 123
                  to: {}
                  token_address: string_value
                  token_id: string_value
                  transaction_type: string_value
                  tx_hash: string_value
                  tx_hex: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
