openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::account_balance::status
  version: v2
  description: Query the status/response of an account balance request in the Komodo
    DeFi Framework API.
paths:
  /task::account_balance::status:
    post:
      summary: Account Balance Task Status
      description: Query the status/response of an account balance request in the
        Komodo DeFi Framework API.
      operationId: task::account_balance::status
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::account_balance::status
                params:
                  type: object
                  properties:
                    forget_if_finished:
                      description: If `false`, will return final response for completed
                        tasks.
                      type: boolean
                      default: '`true`'
                    task_id:
                      description: The identifying number returned when initiating
                        the task.
                      type: integer
                      default: '`-`'
                  required:
                  - task_id
      responses:
        '200':
          description: Successful response for task::account_balance::status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_account_balance_status_Response'
              example:
                mmrpc: '2.0'
                result:
                  current_block: 123
                  ticker: string_value
                  wallet_balance: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
