openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - lightning::channels
  version: v2
  description: This document provides an overview of all Lightning Network channel
    management methods available in the Komodo DeFi Framework.
paths:
  /lightning::channels:
    post:
      summary: 'Komodo DeFi Framework Method Overview: Lightning Network Channels'
      description: This document provides an overview of all Lightning Network channel
        management methods available in the Komodo DeFi Framework.
      operationId: lightning::channels
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::channels
      responses:
        '200':
          description: Successful response for lightning::channels
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_channels_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
