openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - lightning::channels::open_channel
  version: v2
  description: Open a new Lightning Network channel using the Komodo DeFi Framework
    API.
paths:
  /lightning::channels::open_channel:
    post:
      summary: Open Lightning Channel
      description: Open a new Lightning Network channel using the Komodo DeFi Framework
        API.
      operationId: lightning::channels::open_channel
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::channels::open_channel
      responses:
        '200':
          description: Successful response for lightning::channels::open_channel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_channels_open_channel_Response'
              example:
                mmrpc: '2.0'
                result:
                  uuid: string_value
                  node_address: string_value
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
