openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - lightning::payments::list_payments_by_filter
  version: v2
  description: Returns a list of Lightning Network payments filtered by the provided
    filter object.
paths:
  /lightning::payments::list_payments_by_filter:
    post:
      summary: List Lightning Payments by Filter
      description: Returns a list of Lightning Network payments filtered by the provided
        filter object.
      operationId: lightning::payments::list_payments_by_filter
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::payments::list_payments_by_filter
      responses:
        '200':
          description: Successful response for lightning::payments::list_payments_by_filter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_payments_list_payments_by_filter_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: {}
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
