openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::enable_z_coin::init
  version: v2
  description: Task managed activation of ZHTLC coins like ARRR & ZOMBIE.
paths:
  /task::enable_z_coin::init:
    post:
      summary: 'Enable Z Coin Task: Init'
      description: Task managed activation of ZHTLC coins like ARRR & ZOMBIE.
      operationId: task::enable_z_coin::init
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::enable_z_coin::init
                params:
                  type: object
                  properties:
                    activation_params:
                      description: A standard [ActivationRpcData](/komodo-defi-framework/api/common_structures/activation/#activation-rpc-data)
                        object.
                      type: object
                    ticker:
                      description: Ticker of coin to activate
                      type: string
                  required:
                  - activation_params
                  - ticker
      responses:
        '200':
          description: Successful response for task::enable_z_coin::init
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_enable_z_coin_init_Response'
              example:
                mmrpc: '2.0'
                result:
                  task_id: 123
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
