openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - withdraw
  version: v1
  description: The withdraw method generates, signs, and returns a transaction that
    transfers the amount of coin to the address indicated in the to argument.
paths:
  /withdraw:
    post:
      summary: Withdraw Funds
      description: The withdraw method generates, signs, and returns a transaction
        that transfers the amount of coin to the address indicated in the to argument.
      operationId: withdraw
      tags:
      - withdraw
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - withdraw
      responses:
        '200':
          description: Successful response for withdraw
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/withdraw_Response'
              example:
                mmrpc: '2.0'
                result:
                  from: string_value
                  to: string_value
                  my_balance_change: string_value
                  received_by_me: string_value
                  spent_by_me: string_value
                  total_amount: string_value
                  fee_details: {}
                  tx_hash: string_value
                  tx_hex: string_value
                  coin: string_value
                  kmd_rewards: {}
                  kmd_rewards.amount: string_value
                  kmd_rewards.claimed_by_me: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
