openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - lightning::channels::get_claimable_balances
  version: v2
  description: Get claimable Lightning Network channel balances using the Komodo DeFi
    Framework API.
paths:
  /lightning::channels::get_claimable_balances:
    post:
      summary: Get Claimable Lightning Balances
      description: Get claimable Lightning Network channel balances using the Komodo
        DeFi Framework API.
      operationId: lightning::channels::get_claimable_balances
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::channels::get_claimable_balances
      responses:
        '200':
          description: Successful response for lightning::channels::get_claimable_balances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_channels_get_claimable_balances_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: {}
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
