openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::account_balance
  version: v2
  description: Overview of account balance task-managed methods in the Komodo DeFi
    Framework API.
paths:
  /task::account_balance:
    post:
      summary: Account Balance Task
      description: Overview of account balance task-managed methods in the Komodo
        DeFi Framework API.
      operationId: task::account_balance
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::account_balance
      responses:
        '200':
          description: Successful response for task::account_balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_account_balance_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
