openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::withdraw::status
  version: v2
  description: Get the status of a withdrawal transaction generation in the Komodo
    DeFi Framework API.
paths:
  /task::withdraw::status:
    post:
      summary: Withdraw Task Status
      description: Get the status of a withdrawal transaction generation in the Komodo
        DeFi Framework API.
      operationId: task::withdraw::status
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::withdraw::status
                params:
                  type: object
                  properties:
                    forget_if_finished:
                      description: If `false`, will return final response for completed
                        tasks.
                      type: boolean
                      default: '`true`'
                    task_id:
                      description: The identifying number returned when initiating
                        the initialisation process.
                      type: integer
                      default: '`-`'
                  required:
                  - task_id
      responses:
        '200':
          description: Successful response for task::withdraw::status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_withdraw_status_Response'
              example:
                mmrpc: '2.0'
                result:
                  status: string_value
                  details: {}
                  details.to: string_value
                  details.from: string_value
                  details.my_balance_change: string_value
                  details.received_by_me: string_value
                  details.spent_by_me: string_value
                  details.total_amount: string_value
                  details.fee_details: {}
                  details.tx_hash: string_value
                  details.tx_hex: string_value
                  details.coin: string_value
                  details.transaction_type: string_value
                  details.kmd_rewards: {}
                  details.kmd_rewards.amount: string_value
                  details.kmd_rewards.claimed_by_me: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
