openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::enable_lightning::cancel
  version: v2
  description: Cancel the initialization of a lightning node on the Komodo DeFi Framework.
paths:
  /task::enable_lightning::cancel:
    post:
      summary: Cancel Lightning Activation Task
      description: Cancel the initialization of a lightning node on the Komodo DeFi
        Framework.
      operationId: task::enable_lightning::cancel
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::enable_lightning::cancel
                params:
                  type: object
                  properties:
                    task_id:
                      description: The task id returned from `task::enable_lightning::init`
                      type: integer
                  required:
                  - task_id
      responses:
        '200':
          description: Successful response for task::enable_lightning::cancel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_enable_lightning_cancel_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
