openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - get_trade_fee
  version: v1
  description: The get_trade_fee method returns the approximate amount of the miner
    fee that is paid per swap transaction.
paths:
  /get_trade_fee:
    post:
      summary: Get Trade Fee
      description: The get_trade_fee method returns the approximate amount of the
        miner fee that is paid per swap transaction.
      operationId: get_trade_fee
      tags:
      - get_trade_fee
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - get_trade_fee
      responses:
        '200':
          description: Successful response for get_trade_fee
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_trade_fee_Response'
              example:
                mmrpc: '2.0'
                result:
                  coin: string_value
                  amount: string_value
                  amount_rat: {}
                  amount_fraction: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
