openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - send_raw_transaction
  version: v1
  description: The send_raw_transaction method broadcasts the transaction to the network
    of the selected coin.
paths:
  /send_raw_transaction:
    post:
      summary: Send Raw Transaction
      description: The send_raw_transaction method broadcasts the transaction to the
        network of the selected coin.
      operationId: send_raw_transaction
      tags:
      - send_raw_transaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - send_raw_transaction
      responses:
        '200':
          description: Successful response for send_raw_transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/send_raw_transaction_Response'
              example:
                mmrpc: '2.0'
                result:
                  tx_hash: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
