openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - Overview
  version: v2
  description: This document provides an overview of all available methods for the
    Lightning Network on the Komodo DeFi Framework.
paths:
  /Overview:
    post:
      summary: 'Komodo DeFi Framework Method Overview: Lightning Network Methods'
      description: This document provides an overview of all available methods for
        the Lightning Network on the Komodo DeFi Framework.
      operationId: Overview
      tags:
      - Overview
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - Overview
      responses:
        '200':
          description: Successful response for Overview
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Overview_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
