openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - show_priv_key
  version: v1
  description: The show_priv_key method returns the private key of the specified coin
    in a format compatible with coin wallets.
paths:
  /show_priv_key:
    post:
      summary: Show Priv Key
      description: The show_priv_key method returns the private key of the specified
        coin in a format compatible with coin wallets.
      operationId: show_priv_key
      tags:
      - show_priv_key
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - show_priv_key
      responses:
        '200':
          description: Successful response for show_priv_key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/show_priv_key_Response'
              example:
                mmrpc: '2.0'
                result:
                  coin: string_value
                  priv_key: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
