openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::enable_utxo::init
  version: v2
  description: Task managed activation of UTXO coins like KMD, LTC, BTC & DOGE.
paths:
  /task::enable_utxo::init:
    post:
      summary: 'Enable UTXO Task: Init'
      description: Task managed activation of UTXO coins like KMD, LTC, BTC & DOGE.
      operationId: task::enable_utxo::init
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::enable_utxo::init
                params:
                  type: object
                  properties:
                    activation_params:
                      description: A standard [ActivationParams](/komodo-defi-framework/api/common_structures/activation/#activation-params)
                        object containing activation configuration parameters for
                        UTXO coins.
                      type: object
                      default: '-'
                    priv_key_policy:
                      description: Value can be [PrivKeyActivationPolicyEnum](/komodo-defi-framework/api/common_structures/enums/#priv-key-activation-policy-enum).
                      $ref: '#/components/schemas/priv-key-activation-policy-enum'
                      default: '`ContextPrivKey`'
                    ticker:
                      description: Ticker of the UTXO-based coin you want to enable.
                      type: string
                      default: '-'
                  required:
                  - activation_params
                  - ticker
      responses:
        '200':
          description: Successful response for task::enable_utxo::init
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_enable_utxo_init_Response'
              example:
                mmrpc: '2.0'
                result:
                  task_id: 123
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
