openapi: 3.0.3
info:
  title: Komodo DeFi Framework UTXO Coin Activation API
  version: 1.0.3
  description: Modular OpenAPI spec for task managed UTXO coin activation.
servers:
  - url: /
tags:
  - name: UTXO Activation
    description: Methods for task managed activation of UTXO coins
paths:
  /v2/task/enable_utxo/init:
    $ref: './paths/v2/enable_utxo_init.yaml'
  /v2/task/enable_utxo/status:
    $ref: './paths/v2/enable_utxo_status.yaml'
  /v2/task/enable_utxo/user_action:
    $ref: './paths/v2/enable_utxo_user_action.yaml'
  /v2/task/enable_utxo/cancel:
    $ref: './paths/v2/enable_utxo_cancel.yaml'
  /v2/task/enable_bch/init:
    $ref: './paths/v2/enable_bch_init.yaml'
  /v2/task/enable_bch/status:
    $ref: './paths/v2/enable_bch_status.yaml'
  /v2/task/enable_bch/user_action:
    $ref: './paths/v2/enable_bch_user_action.yaml'
  /v2/task/enable_bch/cancel:
    $ref: './paths/v2/enable_bch_cancel.yaml'
  /v2/task/enable_eth/init:
    $ref: './paths/v2/enable_eth_init.yaml'
  /v2/task/enable_eth/status:
    $ref: './paths/v2/enable_eth_status.yaml'
  /v2/task/enable_eth/user_action:
    $ref: './paths/v2/enable_eth_user_action.yaml'
  /v2/task/enable_eth/cancel:
    $ref: './paths/v2/enable_eth_cancel.yaml'
  /v2/task/enable_qtum/init:
    $ref: './paths/v2/enable_qtum_init.yaml'
  /v2/task/enable_qtum/status:
    $ref: './paths/v2/enable_qtum_status.yaml'
  /v2/task/enable_qtum/user_action:
    $ref: './paths/v2/enable_qtum_user_action.yaml'
  /v2/task/enable_qtum/cancel:
    $ref: './paths/v2/enable_qtum_cancel.yaml'
  /v2/task/enable_tendermint/init:
    $ref: './paths/v2/enable_tendermint_init.yaml'
  /v2/task/enable_tendermint/status:
    $ref: './paths/v2/enable_tendermint_status.yaml'
  /v2/task/enable_tendermint/user_action:
    $ref: './paths/v2/enable_tendermint_user_action.yaml'
  /v2/task/enable_tendermint/cancel:
    $ref: './paths/v2/enable_tendermint_cancel.yaml'
  /v2/task/enable_z_coin/init:
    $ref: './paths/v2/enable_z_coin_init.yaml'
  /v2/task/enable_z_coin/status:
    $ref: './paths/v2/enable_z_coin_status.yaml'
  /v2/task/enable_z_coin/user_action:
    $ref: './paths/v2/enable_z_coin_user_action.yaml'
  /v2/task/enable_z_coin/cancel:
    $ref: './paths/v2/enable_z_coin_cancel.yaml'
  /v2/enable_bch_with_tokens:
    $ref: './paths/v2/enable_bch_with_tokens.yaml'
  /v2/enable_eth_with_tokens:
    $ref: './paths/v2/enable_eth_with_tokens.yaml'
  /v2/enable_tendermint_with_assets:
    $ref: './paths/v2/enable_tendermint_with_assets.yaml'
  /v2/enable_slp:
    $ref: './paths/v2/enable_slp.yaml'
  /v2/enable_erc20:
    $ref: './paths/v2/enable_erc20.yaml'
  /v2/enable_tendermint_token:
    $ref: './paths/v2/enable_tendermint_token.yaml'
  /v2/task/enable_lightning/init:
    $ref: './paths/v2/enable_lightning_init.yaml'
  /v2/task/enable_lightning/status:
    $ref: './paths/v2/enable_lightning_status.yaml'
  /v2/task/enable_lightning/cancel:
    $ref: './paths/v2/enable_lightning_cancel.yaml'
  /v2/lightning/channels/open_channel:
    $ref: './paths/v2/lightning_channels_open_channel.yaml'
  /v2/lightning/channels/close_channel:
    $ref: './paths/v2/lightning_channels_close_channel.yaml'
  /v2/lightning/channels/update_channel:
    $ref: './paths/v2/lightning_channels_update_channel.yaml'
  /v2/lightning/channels/get_channel_details:
    $ref: './paths/v2/lightning_channels_get_channel_details.yaml'
  /v2/lightning/channels/get_claimable_balances:
    $ref: './paths/v2/lightning_channels_get_claimable_balances.yaml'
  /v2/lightning/channels/list_open_channels_by_filter:
    $ref: './paths/v2/lightning_channels_list_open_channels_by_filter.yaml'
  /v2/lightning/channels/list_closed_channels_by_filter:
    $ref: './paths/v2/lightning_channels_list_closed_channels_by_filter.yaml'
  /v2/lightning/nodes/connect_to_node:
    $ref: './paths/v2/lightning_nodes_connect_to_node.yaml'
  /v2/lightning/nodes/list_trusted_nodes:
    $ref: './paths/v2/lightning_nodes_list_trusted_nodes.yaml'
  /v2/lightning/nodes/add_trusted_node:
    $ref: './paths/v2/lightning_nodes_add_trusted_node.yaml'
  /v2/lightning/nodes/remove_trusted_node:
    $ref: './paths/v2/lightning_nodes_remove_trusted_node.yaml'
  /v2/lightning/payments/generate_invoice:
    $ref: './paths/v2/lightning_payments_generate_invoice.yaml'
  /v2/lightning/payments/send_payment:
    $ref: './paths/v2/lightning_payments_send_payment.yaml'
  /v2/lightning/payments/get_payment_details:
    $ref: './paths/v2/lightning_payments_get_payment_details.yaml'
  /v2/lightning/payments/list_payments_by_filter:
    $ref: './paths/v2/lightning_payments_list_payments_by_filter.yaml'
  /v2/withdraw_nft:
    $ref: './paths/v2/withdraw_nft.yaml'
  /v2/get_nft_list:
    $ref: './paths/v2/get_nft_list.yaml'
  /v2/get_nft_metadata:
    $ref: './paths/v2/get_nft_metadata.yaml'
  /v2/get_nft_transfers:
    $ref: './paths/v2/get_nft_transfers.yaml'
  /v2/query_nft_database_tables:
    $ref: './paths/v2/query_nft_database_tables.yaml'
  /v2/stream/balance/enable:
    $ref: './paths/v2/stream_balance_enable.yaml'
  /v2/stream/disable:
    $ref: './paths/v2/stream_disable.yaml'
  /v2/stream/fee_estimator/enable:
    $ref: './paths/v2/stream_fee_estimator_enable.yaml'
  /v2/stream/heartbeat/enable:
    $ref: './paths/v2/stream_heartbeat_enable.yaml'
  /v2/stream/network/enable:
    $ref: './paths/v2/stream_network_enable.yaml'
  /v2/stream/order_status/enable:
    $ref: './paths/v2/stream_order_status_enable.yaml'
  /v2/stream/orderbook/enable:
    $ref: './paths/v2/stream_orderbook_enable.yaml'
  /v2/stream/swap_status/enable:
    $ref: './paths/v2/stream_swap_status_enable.yaml'
  /v2/stream/tx_history/enable:
    $ref: './paths/v2/stream_tx_history_enable.yaml'
  /v2/swaps_and_orders/stop_simple_market_maker_bot:
    $ref: './paths/v2/stop_simple_market_maker_bot.yaml'
  /v2/swaps_and_orders/get_locked_amount:
    $ref: './paths/v2/get_locked_amount.yaml'
  /v2/swaps_and_orders/max_maker_vol:
    $ref: './paths/v2/max_maker_vol.yaml'
  /v2/swaps_and_orders/my_recent_swaps:
    $ref: './paths/v2/my_recent_swaps.yaml'
  /v2/swaps_and_orders/recreate_swap_data:
    $ref: './paths/v2/recreate_swap_data.yaml'
  /v2/swaps_and_orders/start_simple_market_maker_bot:
    $ref: './paths/v2/start_simple_market_maker_bot.yaml'
  /v2/swaps_and_orders/active_swaps:
    $ref: './paths/v2/active_swaps.yaml'
  /v2/swaps_and_orders/best_orders:
    $ref: './paths/v2/best_orders.yaml'
  /v2/utils/change_mnemonic_password:
    $ref: './paths/v2/utils_change_mnemonic_password.yaml'
  /v2/utils/get_mnemonic:
    $ref: './paths/v2/utils_get_mnemonic.yaml'
  /v2/utils/message_signing_sign_message:
    $ref: './paths/v2/utils_message_signing_sign_message.yaml'
  /v2/utils/message_signing_verify_message:
    $ref: './paths/v2/utils_message_signing_verify_message.yaml'
  /v2/utils/stop_version_stat_collection:
    $ref: './paths/v2/utils_stop_version_stat_collection.yaml'
  /v2/utils/update_version_stat_collection:
    $ref: './paths/v2/utils_update_version_stat_collection.yaml'
  /v2/utils/add_node_to_version_stat:
    $ref: './paths/v2/utils_add_node_to_version_stat.yaml'
  /v2/utils/get_current_mtp:
    $ref: './paths/v2/utils_get_current_mtp.yaml'
  /v2/utils/get_enabled_coins:
    $ref: './paths/v2/utils_get_enabled_coins.yaml'
  /v2/wallet/fee_management/get_eth_estimated_fee_per_gas:
    $ref: './paths/v2/wallet_fee_management_get_eth_estimated_fee_per_gas.yaml'
  /v2/wallet/fee_management/get_swap_transaction_fee_policy:
    $ref: './paths/v2/wallet_fee_management_get_swap_transaction_fee_policy.yaml'
  /v2/wallet/fee_management/set_swap_transaction_fee_policy:
    $ref: './paths/v2/wallet_fee_management_set_swap_transaction_fee_policy.yaml'
  /v2/wallet/get_wallet_names:
    $ref: './paths/v2/wallet_get_wallet_names.yaml'
  /v2/wallet/task_managed/account_balance:
    $ref: './paths/v2/wallet_task_managed_account_balance.yaml'
  /v2/wallet/task_managed/create_new_account:
    $ref: './paths/v2/wallet_task_managed_create_new_account.yaml'
  /v2/wallet/task_managed/get_new_address:
    $ref: './paths/v2/wallet_task_managed_get_new_address.yaml'
  /v2/wallet/task_managed/scan_for_new_addresses:
    $ref: './paths/v2/wallet_task_managed_scan_for_new_addresses.yaml'
  /v2/wallet/task_managed/withdraw:
    $ref: './paths/v2/wallet_task_managed_withdraw.yaml'
  /v2/wallet/staking/add_delegation:
    $ref: './paths/v2/wallet_staking_add_delegation.yaml'
  /v2/wallet/staking/get_staking_infos:
    $ref: './paths/v2/wallet_staking_get_staking_infos.yaml'
  /v2/wallet/staking/remove_delegation:
    $ref: './paths/v2/wallet_staking_remove_delegation.yaml'
  /v2/wallet/tx/zhtlc_tx_history:
    $ref: './paths/v2/wallet_tx_zhtlc_tx_history.yaml'
  /v2/wallet/tx/withdraw:
    $ref: './paths/v2/wallet_tx_withdraw.yaml'
  /v2/wallet/tx/my_tx_history:
    $ref: './paths/v2/wallet_tx_my_tx_history.yaml'
  /v2/wallet/tx/get_raw_transaction:
    $ref: './paths/v2/wallet_tx_get_raw_transaction.yaml'
  /v2/wallet/tx/sign_raw_transaction:
    $ref: './paths/v2/wallet_tx_sign_raw_transaction.yaml'
  /v1/active_swaps:
    # @legacy
    $ref: './paths/v1/active_swaps.yaml'
  /v2/one_inch_v6_0_classic_swap_create:
    $ref: './paths/v2/one_inch_v6_0_classic_swap_create.yaml'
  /v2/one_inch_v6_0_classic_swap_liquidity_sources:
    $ref: './paths/v2/one_inch_v6_0_classic_swap_liquidity_sources.yaml'
  /v2/one_inch_v6_0_classic_swap_quote:
    $ref: './paths/v2/one_inch_v6_0_classic_swap_quote.yaml'
  /v2/one_inch_v6_0_classic_swap_tokens:
    $ref: './paths/v2/one_inch_v6_0_classic_swap_tokens.yaml'
  /v2/approve_token:
    $ref: './paths/v2/approve_token.yaml'
  /v2/get_token_allowance:
    $ref: './paths/v2/get_token_allowance.yaml'
components:
  securitySchemes:
    userpass:
      type: apiKey
      in: header
      name: userpass
      description: The API key for authentication. Use the 'userpass' value from your Komodo DeFi Framework instance.
  schemas:
    Activation:
      $ref: './components/schemas/Activation.yaml'
    Lightning:
      $ref: './components/schemas/Lightning.yaml'
    Nfts:
      $ref: './components/schemas/Nfts.yaml'
    Orders:
      $ref: './components/schemas/Orders.yaml'
    Swaps:
      $ref: './components/schemas/Swaps.yaml'
    MakerEvents:
      $ref: './components/schemas/MakerEvents.yaml'
    TakerEvents:
      $ref: './components/schemas/TakerEvents.yaml'
    Wallet:
      $ref: './components/schemas/Wallet.yaml' 