components:
  schemas:
    Activation:
      $ref: './components/schemas/Activation.yaml'
    Wallet:
      $ref: './components/schemas/Wallet.yaml'
    Swaps:
      $ref: './components/schemas/Swaps.yaml'
    Orders:
      $ref: './components/schemas/Orders.yaml'
    Nfts:
      $ref: './components/schemas/Nfts.yaml'
    Lightning:
      $ref: './components/schemas/Lightning.yaml' 