openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - get_token_info
  version: v2
  description: The `get_token_info` method returns the ticker and decimals values
    (required for activation) given a platform and contract as input.
paths:
  /get_token_info:
    post:
      summary: Get Token Info
      description: The `get_token_info` method returns the ticker and decimals values
        (required for activation) given a platform and contract as input.
      operationId: get_token_info
      tags:
      - get_token_info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - get_token_info
                params:
                  type: object
                  properties:
                    protocol:
                      description: A standard [TokenProtocol](/komodo-defi-framework/api/common_structures/nfts/#token-protocol)
                        object.
                      type: object
                  required:
                  - protocol
      responses:
        '200':
          description: Successful response for get_token_info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_token_info_Response'
              example:
                mmrpc: '2.0'
                result:
                  type: string_value
                  info.symbol: string_value
                  info.decimals: 123
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
