openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::withdraw
  version: v2
  description: Overview of withdraw task-managed methods in the Komodo DeFi Framework
    API.
paths:
  /task::withdraw:
    post:
      summary: Withdraw Task Overview
      description: Overview of withdraw task-managed methods in the Komodo DeFi Framework
        API.
      operationId: task::withdraw
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::withdraw
      responses:
        '200':
          description: Successful response for task::withdraw
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_withdraw_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
