openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - get_swap_transaction_fee_policy
  version: v2
  description: Method description for get_swap_transaction_fee_policy
paths:
  /get_swap_transaction_fee_policy:
    post:
      summary: Get Swap Transaction Fee Policy
      description: Method description for get_swap_transaction_fee_policy
      operationId: get_swap_transaction_fee_policy
      tags:
      - get_swap_transaction_fee_policy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - get_swap_transaction_fee_policy
                params:
                  type: object
                  properties:
                    coin:
                      description: Ticker of the supported ETH/EVM coin or asset for
                        which you want to view the fee policy.
                      type: string
                  required:
                  - coin
      responses:
        '200':
          description: Successful response for get_swap_transaction_fee_policy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_swap_transaction_fee_policy_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
