openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - message_signing
  version: v2
  description: This document provides an overview of message signing and verification
    methods available in the Komodo DeFi Framework.
paths:
  /message_signing:
    post:
      summary: 'Komodo DeFi Framework Method Overview: Message Signing and Verification'
      description: This document provides an overview of message signing and verification
        methods available in the Komodo DeFi Framework.
      operationId: message_signing
      tags:
      - message_signing
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - message_signing
      responses:
        '200':
          description: Successful response for message_signing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/message_signing_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
