openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::init_trezor::init
  version: v2
  description: Initialise your Trezor device for use in the Komodo DeFi Framework
    API.
paths:
  /task::init_trezor::init:
    post:
      summary: task::init_trezor::init
      description: Initialise your Trezor device for use in the Komodo DeFi Framework
        API.
      operationId: task::init_trezor::init
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::init_trezor::init
      responses:
        '200':
          description: Successful response for task::init_trezor::init
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_init_trezor_init_Response'
              example:
                mmrpc: '2.0'
                result:
                  task_id: 123
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
