openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - lightning::payments::get_payment_details
  version: v2
  description: Get details of a Lightning Network payment using the Komodo DeFi Framework
    API.
paths:
  /lightning::payments::get_payment_details:
    post:
      summary: Get Lightning Payment Details
      description: Get details of a Lightning Network payment using the Komodo DeFi
        Framework API.
      operationId: lightning::payments::get_payment_details
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::payments::get_payment_details
      responses:
        '200':
          description: Successful response for lightning::payments::get_payment_details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_payments_get_payment_details_Response'
              example:
                mmrpc: '2.0'
                result:
                  payment_details: {}
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
