openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - enable_tendermint_token
  version: v2
  description: Method description for enable_tendermint_token
paths:
  /enable_tendermint_token:
    post:
      summary: Enable Tendermint Token
      description: Method description for enable_tendermint_token
      operationId: enable_tendermint_token
      tags:
      - enable_tendermint_token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - enable_tendermint_token
      responses:
        '200':
          description: Successful response for enable_tendermint_token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/enable_tendermint_token_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
