openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::enable_utxo::cancel
  version: v2
  description: Cancel the UTXO activation task before completion.
paths:
  /task::enable_utxo::cancel:
    post:
      summary: 'Enable UTXO Task: Cancel'
      description: Cancel the UTXO activation task before completion.
      operationId: task::enable_utxo::cancel
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::enable_utxo::cancel
                params:
                  type: object
                  properties:
                    task_id:
                      description: The identifying number returned when initiating
                        the enabling process.
                      type: integer
                  required:
                  - task_id
      responses:
        '200':
          description: Successful response for task::enable_utxo::cancel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_enable_utxo_cancel_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                  error: string_value
                  error_path: string_value
                  error_trace: string_value
                  error_type: string_value
                  error_data: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
