openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - get_mnemonic
  version: v2
  description: The get_mnemonic method returns the user
paths:
  /get_mnemonic:
    post:
      summary: Get Mnemonic
      description: The get_mnemonic method returns the user
      operationId: get_mnemonic
      tags:
      - get_mnemonic
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - get_mnemonic
                params:
                  type: object
                  properties:
                    format:
                      description: Either `encrypted` or `plaintext`. Defaults to
                        `encrypted`.
                      type: string
                      default: '`encrypted`'
                    password:
                      description: The password to decrypt your stored mnemonic phrase.
                        Only required if `plaintext` format is requested.
                      type: string
                      default: '`-`'
      responses:
        '200':
          description: Successful response for get_mnemonic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_mnemonic_Response'
              example:
                mmrpc: '2.0'
                result:
                  format: string_value
                  mnemonic: string_value
                  encrypted_mnemonic_data: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
