services:
  # ---------------------------------------------------------------------
  # Primary KDF node used by most existing tests (alias: node-A)
  # ---------------------------------------------------------------------
  kdf_node_a:
    image: kdf-dev-env:latest
    build:
      context: .
      dockerfile: Dockerfile.kdf
      args:
        # This can still be used by the final image
        RPC_PORT: ${RPC_PORT:-7783}
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    ports:
      - "${RPC_PORT:-7783}:${RPC_PORT:-7783}"
      - "42845:42845" # TCP p2p
      - "42855:42855" # WSS p2p
    volumes:
      - ./kdf-db:/home/kdfuser/.kdf/DB
      - ./kdf-config/MM2.json:/home/kdfuser/.kdf/MM2.json
      - ./kdf-config/coins:/home/kdfuser/.kdf/coins
      - ./kdf-config/.env:/home/kdfuser/.kdf/.env

  # ---------------------------------------------------------------------
  # Secondary KDF node (node-B) – used for maker/taker or peer-to-peer tests.
  # It listens on a different RPC & p2p port and stores data in its own
  # bind-mount to avoid conflicts with node-A.
  # ---------------------------------------------------------------------
  kdf_node_b:
    image: kdf-dev-env:latest
    build:
      context: .
      dockerfile: Dockerfile.kdf
      args:
        RPC_PORT: ${RPC_PORT_NODE_B:-7784}
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    ports:
      - "${RPC_PORT_NODE_B:-7784}:${RPC_PORT_NODE_B:-7784}"
      - "42846:42845"  # forward container 42845 → host 42846 (TCP)
      - "42856:42855"  # forward container 42855 → host 42856 (WSS)
    volumes:
      - ./kdf-db-node-b:/home/kdfuser/.kdf/DB
      - ./kdf-config-node-b/MM2.json:/home/kdfuser/.kdf/MM2.json
      - ./kdf-config/coins:/home/kdfuser/.kdf/coins:ro

  # ---------------------------------------------------------------------
  # Ganache – lightweight EVM dev-chain used by WalletConnect / EVM tests.
  # Exposes JSON-RPC on 8545 with deterministic accounts pre-funded.
  # Resource footprint: ~200 MB RAM, negligible CPU when idle.
  # ---------------------------------------------------------------------
  ganache:
    image: trufflesuite/ganache:v7.7.7
    command: [
      "--host", "0.0.0.0",
      "--port", "8545",
      "--chain.chainId", "1337",
      "--wallet.totalAccounts", "10",
      "--wallet.defaultBalance", "1000"
    ]
    ports:
      - "8545:8545"

volumes:
  kdf-db: {}
  kdf-db-node-b: {} 