services:
  kdf:
    image: ${KDF_IMAGE:-kdf-image:latest}
    build:
      context: .
      dockerfile: Dockerfile.kdf
      args:
        KDF_BRANCH: ${KDF_BRANCH:-sia-rc-cleanup}
        RPC_PORT: ${RPC_PORT:-7783}
    ports:
      - "${RPC_PORT:-7783}:${RPC_PORT:-7783}"
    volumes:
      - ./kdf-db:/root/.kdf/DB
      - ./kdf-config/MM2.json:/root/.kdf/MM2.json
      - ./kdf-config/coins:/root/.kdf/coins
      - ./kdf-config/.env:/root/.kdf/.env
    command: ["/bin/sh", "-c", "/kdf/target/release/kdf "]
volumes:
  kdf-db:
  kdf-config: 