services:
  kdf:
    image: kdf-dev-env:latest
    build:
      context: .
      dockerfile: Dockerfile.kdf
      args:
        # This can still be used by the final image
        RPC_PORT: ${RPC_PORT:-7783}
    ports:
      - "${RPC_PORT:-7783}:${RPC_PORT:-7783}"
      - "42845:42845" # TCP p2p
      - "42855:42855" # WSS p2p
    volumes:
      - ./docker/kdf-db:/root/.kdf/DB
      - ./docker/kdf-config/MM2.json:/root/.kdf/MM2.json
      - ./docker/kdf-config/coins:/root/.kdf/coins
      - ./docker/kdf-config/.env:/root/.kdf/.env


volumes:
  kdf-db: {} 