openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::enable_qtum::cancel
  version: v2
  description: Cancel the QTUM activation task.
paths:
  /task::enable_qtum::cancel:
    post:
      summary: task::enable_qtum::cancel
      description: Cancel the QTUM activation task.
      operationId: task::enable_qtum::cancel
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::enable_qtum::cancel
      responses:
        '200':
          description: Successful response for task::enable_qtum::cancel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_enable_qtum_cancel_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                  error: string_value
                  error_path: string_value
                  error_trace: string_value
                  error_type: string_value
                  error_data: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
