openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - get_my_peer_id
  version: v1
  description: The get_my_peer_id method returns your unique identifying Peer ID on
    the network.
paths:
  /get_my_peer_id:
    post:
      summary: Get My Peer ID
      description: The get_my_peer_id method returns your unique identifying Peer
        ID on the network.
      operationId: get_my_peer_id
      tags:
      - get_my_peer_id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - get_my_peer_id
      responses:
        '200':
          description: Successful response for get_my_peer_id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_my_peer_id_Response'
              example:
                mmrpc: '2.0'
                result:
                  PeerID: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
