openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - active_swaps
  version: v1
  description: Method description for active_swaps
paths:
  /active_swaps:
    post:
      summary: Active Swaps
      description: Method description for active_swaps
      operationId: active_swaps
      tags:
      - active_swaps
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - active_swaps
      responses:
        '200':
          description: Successful response for active_swaps
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/active_swaps_Response'
              example:
                mmrpc: '2.0'
                result:
                  statuses: {}
                  uuids: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
