openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - utils
  version: v2
  description: This document provides an overview of all utility methods available
    in the Komodo DeFi Framework.
paths:
  /utils:
    post:
      summary: 'Komodo DeFi Framework Method Overview: Utility Methods'
      description: This document provides an overview of all utility methods available
        in the Komodo DeFi Framework.
      operationId: utils
      tags:
      - utils
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - utils
      responses:
        '200':
          description: Successful response for utils
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/utils_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
