openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - get_gossip_topic_peers
  version: v1
  description: The get_gossip_topic_peers method returns a map of topics to an array
    of the PeerIDs which are subscribers.
paths:
  /get_gossip_topic_peers:
    post:
      summary: Get Gossip Topic Peers
      description: The get_gossip_topic_peers method returns a map of topics to an
        array of the PeerIDs which are subscribers.
      operationId: get_gossip_topic_peers
      tags:
      - get_gossip_topic_peers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - get_gossip_topic_peers
      responses:
        '200':
          description: Successful response for get_gossip_topic_peers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_gossip_topic_peers_Response'
              example:
                mmrpc: '2.0'
                result:
                  Topic-PeerID map: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
