openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - lightning::nodes::add_trusted_node
  version: v2
  description: Add a trusted Lightning node using the Komodo DeFi Framework API.
paths:
  /lightning::nodes::add_trusted_node:
    post:
      summary: Add Trusted Lightning Node
      description: Add a trusted Lightning node using the Komodo DeFi Framework API.
      operationId: lightning::nodes::add_trusted_node
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::nodes::add_trusted_node
      responses:
        '200':
          description: Successful response for lightning::nodes::add_trusted_node
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_nodes_add_trusted_node_Response'
              example:
                mmrpc: '2.0'
                result:
                  added_node: string_value
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
