openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - task::scan_for_new_addresses::init
  version: v2
  description: Initiate a scan for new HD addresses in the Komodo DeFi Framework API.
paths:
  /task::scan_for_new_addresses::init:
    post:
      summary: Initialize Scan For New Addresses Task
      description: Initiate a scan for new HD addresses in the Komodo DeFi Framework
        API.
      operationId: task::scan_for_new_addresses::init
      tags:
      - task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - task::scan_for_new_addresses::init
                params:
                  type: object
                  properties:
                    account_id:
                      description: HD wallets only. Generally this will be `0` unless
                        you have multiple accounts registered on your HD wallet
                      type: integer
                      default: '`0`'
                    coin:
                      description: The ticker of the coin you want to scan addresses
                        for
                      type: string
                      default: '`-`'
                    gap_limit:
                      description: The maximum number of empty addresses in a row.
                        Defaults to the value provided on activation or 20 if no value
                        was provided
                      type: integer
                      default: '`20`'
                  required:
                  - coin
      responses:
        '200':
          description: Successful response for task::scan_for_new_addresses::init
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task_scan_for_new_addresses_init_Response'
              example:
                mmrpc: '2.0'
                result:
                  task_id: 123
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
