openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - stop_version_stat_collection
  version: v2
  description: The stop_version_stat_collection method stops the collection of version
    stats at the end of the current loop interval.
paths:
  /stop_version_stat_collection:
    post:
      summary: Stop Version Stat Collection
      description: The stop_version_stat_collection method stops the collection of
        version stats at the end of the current loop interval.
      operationId: stop_version_stat_collection
      tags:
      - stop_version_stat_collection
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - stop_version_stat_collection
      responses:
        '200':
          description: Successful response for stop_version_stat_collection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stop_version_stat_collection_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
