openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - my_recent_swaps
  version: v2
  description: The my_recent_swaps method returns the data of the most recent atomic
    swaps executed by the Komodo DeFi Framework API node.
paths:
  /my_recent_swaps:
    post:
      summary: My Recent Swaps
      description: The my_recent_swaps method returns the data of the most recent
        atomic swaps executed by the Komodo DeFi Framework API node.
      operationId: my_recent_swaps
      tags:
      - my_recent_swaps
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - my_recent_swaps
                params:
                  type: object
                  properties:
                    from_timestamp:
                      description: Start timestamp in UNIX format
                      type: integer
                      default: '-'
                    from_uuid:
                      description: The UUID from which to start fetching results
                      type: string
                      default: '-'
                    limit:
                      description: The maximum number of results to return
                      type: integer
                      default: '`10`'
                    my_coin:
                      description: Coin being used by you for the swap/trade.
                      type: string
                      default: '-'
                    other_coin:
                      description: Coin you are trading against
                      type: string
                      default: '-'
                    page_number:
                      description: Offset for paginated results
                      type: integer
                      default: '`1`'
                    to_timestamp:
                      description: End timestamp in UNIX format
                      type: integer
                      default: '-'
      responses:
        '200':
          description: Successful response for my_recent_swaps
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/my_recent_swaps_Response'
              example:
                mmrpc: '2.0'
                result:
                  found_records: 123
                  from_uuid: string_value
                  limit: 123
                  page_number: 123
                  skipped: 123
                  swaps: {}
                  total: 123
                  total_pages: 123
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
