openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Max Taker Vol API
  version: v1
  description: OpenAPI specification for the max_taker_vol methods.
paths:
  /max_taker_vol:
    post:
      summary: Max Taker Vol
      description: The max_taker_vol method returns the maximum available volume for
        buy/sell methods for selected coin.
      operationId: max_taker_vol
      tags:
      - max_taker_vol
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - max_taker_vol
      responses:
        '200':
          description: Successful response for max_taker_vol
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/max_taker_vol_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
