openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Stop API
  version: v1
  description: OpenAPI specification for the stop methods.
paths:
  /stop:
    post:
      summary: Stop
      description: The stop method stops the Komodo DeFi Framework API software.
      operationId: stop
      tags:
      - stop
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - stop
      responses:
        '200':
          description: Successful response for stop
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stop_Response'
              example:
                mmrpc: '2.0'
                result:
                  '-': {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
