openapi: 3.0.0
info:
  title: Komodo DeFi Framework API - stream::disable
  version: v2
  description: Using this method, you can disable specific streaming events.
paths:
  /stream::disable:
    post:
      summary: Disable Streaming
      description: Using this method, you can disable specific streaming events.
      operationId: stream::disable
      tags:
      - stream
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              - params
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - stream::disable
                params:
                  type: object
                  properties:
                    client_id:
                      description: This ID can be used to access data (e.g. via [http://localhost:7783/event-stream?id=1](http://localhost:7783/event-stream?id=1))
                      type: integer
                    streamer_id:
                      description: An identifier for the data stream to disable.
                      type: string
                  required:
                  - client_id
                  - streamer_id
      responses:
        '200':
          description: Successful response for stream::disable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_disable_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
